---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2020/3/25 19:59
---
local gold_value = 1000000
local gold__ = 2000
local gold_ = "金条"

local dk = {
    {
        {"强效金创药", "超级金创药"},
        {"强效魔法药", "超级魔法药"},
        --{"金创药(中量)", "金创药(中)包"},
        --{"魔法药(中量)", "魔法药(中)包"},
        {"强效太阳水", "强效太阳包"},
        {"万年雪霜", "雪霜包"},

    },
    {
        {"地牢逃脱卷", "地牢逃脱卷包"},
        {"随机传送卷", "随机传送卷包"},
        {"回城卷", "回城卷包"},
        {"行会回城卷", "行会回城卷包"},
    },
}


local zj = {
    "九尾冰狐",
    "大角羊",
    "绝影豹",
    "熔岩犀牛",
    "九尾火狐",
    "黄色狮鹫"
}

function main(npc, player)
    lualib:SetPanelSize(npc, 400, 200)
    local msg = "\n  大人，您有什么需要我帮您保管的吗？\n"
    msg = msg.."  我这除了物品，金币也是可以保管的，\n"
    msg = msg.."  放心，在我这保管是很安全的。\n\n"
    msg = msg.."  <@InfoWarehouse *01*打开>仓库\n"
    msg = msg.."  <@Jin_DH *01*兑换>金条金币\n"
    msg = msg.."  <@jbjm *01*坐骑解绑>金条金币\n"
    msg = msg.."  <@mbind  *01*打捆>各种卷书和药水\n"


    local map_name = lualib:Name(lualib:MapGuid(player))
    if map_name == "庄园" then
        --msg = msg.."\n\n\n<@move_map  *01*返回盟重土城>\n"
    end
    return msg
end

function move_map(npc, player)
    lualib:Player_MapMoveXY(player, "龙城", 248, 273, 3)
    return ""
end




function InfoWarehouse(npc, player)
    lualib:OpenWarehouse(npc, player)
    return ""
end

function OpenWarehouseAdv(npc, player)
    lualib:OpenWarehouseAdv(npc, player)
    return ""
end

--打捆
function mbind(npc, player)
    lualib:SetPanelSize(npc, 400, 200)
    local msg = "\n  你知道我是什么人吗?\n  我做的是这样的事情...\n  你要试一下吗?有什么要拜托的就说吧!\n\n"
    msg = msg.."  <@bind#1 *01*捆>药水\n"
    msg = msg.."  <@bind#2 *01*捆>卷书\n\n"
    msg = msg.."  <@main *01*返回>\n"
    return msg
end

--坐骑解绑
function jbjm(npc, player)
    lualib:SetPanelSize(npc, 400, 200)
    local msg = "\n  解除绑定需要10000元宝！！请慎重点击！！\n\n"
    msg = msg.."  <@jiebang#1 *01*九尾冰狐>\n"
    msg = msg.."  <@jiebang#2 *01*大角羊>\n"
    msg = msg.."  <@jiebang#3 *01*绝影豹>\n"
    msg = msg.."  <@jiebang#4 *01*熔岩犀牛>\n"
    msg = msg.."  <@jiebang#5 *01*九尾火狐>\n"
    msg = msg.."  <@jiebang#6 *01*黄色狮鹫>\n"
    msg = msg.."  <@main *01*返回>\n"
    return msg
end

function jiebang(npc,player,num)
    local num = tonumber(num)
    local count = lualib:ItemCountEx(player,zj[num],1,false,true,false,false)
    if count < 1 then
        lualib:MsgBox(player,"您背包内没有"..zj[num].."坐骑或是没有绑定的该坐骑！！！")
        return ""
    end
    if not lualib:Player_SubIngot(player,10000,false,"坐骑解除绑定","仓库") then
        lualib:MsgBox(player,"您的元宝不足10000！！！")
        return ""
    end
    lualib:DelItem(player,zj[num],1,1,"坐骑解除绑定删除绑定坐骑","仓库")
    lualib:AddItem(player,zj[num],1,false,"坐骑解除绑定添加不绑定坐骑","仓库")
    lualib:MsgBox(player,"解除成功！请查看背包！！")
    return ""
end

function bind(npc, player, types)
    lualib:SetPanelSize(npc, 400, 200)
    local types = tonumber(types)
    local msg = ""
    for i = 1, #dk[types] do
        msg = msg.."\n    <@bindEx#"..types.."#"..i.." *01*捆>  "..dk[types][i][1].."\n"
    end
    msg = msg.."\n    <@main *01*返回>\n"
    return msg
end

function bindEx(npc, player, types, item)
    lualib:SetPanelSize(npc, 400, 200)
    local types = tonumber(types)
    local item = tonumber(item)
    local msg = ""
    local countBind1 = lualib:ItemCountEx(player, dk[types][item][1],1, false, true, false, false)
    local countBind2 = lualib:ItemCountEx(player, dk[types][item][1],0, false, true, false, false)
    if countBind1 < 6 and countBind2 < 6 then
        return "\n  没有找到6个绑定或是6个非绑定的"..dk[types][item][1].."，无法「兑换」。\n\n  <@main *01*返回>"
    else
        if countBind1 >= 6 then
            lualib:DelItem(player, dk[types][item][1], 6,1, "删物品：仓库", player)
            lualib:AddItem(player, dk[types][item][2], 1,true, "给物品：捆", player)
        else
            lualib:DelItem(player, dk[types][item][1], 6,0, "删物品：仓库", player)
            lualib:AddItem(player, dk[types][item][2], 1,false, "给物品：捆", player)
        end


        return "\n  打捆成功!\n \n \n  <@mbind *01*继续打捆>\n\n  <@main *01*返回>"
    end
end
--金币金条「兑换」

function Jin_DH(npc_guid, player_guid)
    lualib:SetPanelSize(npc_guid, 400, 200)
    local msg = "\n  我可以将金币兑换成金条，或将金条兑换成金砖。\n\n"
    msg = msg.."  #OFFSET<Y:3>#金币<@ExchangeGold *01*兑换>金条\n"
    --msg = msg.."  #OFFSET<Y:3>#金条<@ExchangeGoldEx *01*兑换>金币\n"
    msg = msg.."  #OFFSET<Y:3>#金条<@ExchangeGold_2 *01*兑换>金砖\n\n"
    msg = msg.."  <@main *01*返回>\n"
    return msg
end

function ExchangeGold_2(npc, player)
    lualib:SetPanelSize(npc, 400, 200)
    local count = lualib:Player_GetItemCount(player, gold_)
    if count < 5 then
        return "\n  没有5个金条，无法「兑换」。\n\n  <@main *01*返回>"
    end

    local result = lualib:Player_DestroyItem(player, gold_, 5, "删物品：仓库", player)
    if result == false then
        return "系统错误，请联系GM@4！"
    end

    local result = lualib:Player_GiveItemUnbind(player, "金砖", 1, "给物品：金条兑换", "仓库")
    if result == false then
        return "系统错误，请联系GM@3！"
    end
    return "\n  「兑换」金砖成功！\n\n  <@main *01*返回>"
end



function ExchangeGold(npc_guid, player_guid)
    lualib:SetPanelSize(npc_guid, 400, 200)
    if not lualib:Player_IsGoldEnough(player_guid, gold_value, false) then
        return "\n  兑换失败,您的金币不足100万.\n\n  <@main *01*返回>"
    end

    if lualib:Player_GetBagFree(player_guid) < 1 then return "背包满了！" end

    if not lualib:Player_SubGold(player_guid, gold_value, false, "扣金币：仓库将金币「兑换」成金条", "仓库") then
        return "扣除金币失败！"
    end

    local result = lualib:Player_GiveItemUnbind(player_guid, "金条", 1, "给物品：金条兑换", "仓库")
    if result == false then
        return "系统错误，请联系GM@3！"
    end

    lualib:SysMsg_SendTipsMsg(player_guid, "「兑换」金条成功")
    lualib:SysMsg_SendTriggerMsg(player_guid, "「兑换」金条成功")
    return "\n  「兑换」金条成功！\n\n  <@ExchangeGold *01*继续兑换>"
end

function ExchangeGoldEx(npc_guid, player_guid)
    lualib:SetPanelSize(npc_guid, 400, 200)
    local count = lualib:Player_GetItemCount(player_guid, gold_)
    if count < 1 then
        return "\n  没有找到金条，无法「兑换」。\n\n  <@main *01*返回>"
    end

    local result = lualib:Player_DestroyItem(player_guid, gold_, 1, "删物品：仓库", player_guid)
    if result == false then
        return "系统错误，请联系GM@4！"
    end

    if not lualib:Player_AddGold(player_guid, gold_value - gold__, false, "加金币：仓库将金条「兑换」成金币", player_guid) then
        return "\n  给予金币失败！"
    end

    lualib:SysMsg_SendTipsMsg(player_guid, "金币「兑换」成功，数量："..gold_value - gold__.."！")
    lualib:SysMsg_SendTriggerMsg(player_guid, "金币「兑换」成功，数量："..gold_value - gold__.."！")
    return "\n  金币「兑换」成功！\n\n  <@ExchangeGoldEx *01*继续兑换>"
end