---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2020/3/4 13:37
---

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2019/12/28 16:49
---
local maps = {
    ["废矿区东部"] = {"进尸王殿僵尸",60*60*1000},
    ["幻境6"] = {"进幻7尸王",2*60*60*1000},
    ["石窟七层"] = {"进桃园尸王",2*60*60*1000},

}

local monsters = {
    ["进尸王殿僵尸"] = {"废矿区东部",60*60*1000,140,81,"尸王殿入口的洞穴已经打开→→【（废矿东部）140:81】，洞口持续5分钟！！！"},
    ["进幻7尸王"] = {"幻境6",2*60*60*1000,74,30,"幻境七层的入口已经打开了→→【（幻境六层）74:30】，洞口持续5分钟！！！"},
    ["进桃园尸王"] = {"石窟七层",2*60*60*1000,74,30,"桃园密境的入口已经打开了→→【（猪洞七层）74:30】，洞口持续5分钟！！！"},

}

function on_map_create(map,map_keyname)
    if maps[map_keyname] ~= nil then
        lualib:AddTimer(map,777,maps[map_keyname][2],-1,"flush_monster")
    end
    return ""
end


function flush_monster(map,id)
    local map_keyname = lualib:KeyName(map)
    local monster_name = maps[map_keyname][1]
    lualib:Map_RemoveMonster(map,monster_name)
    --lualib:SysMsg_SendBroadcastMsg("移除"..tostring(monster_name), "AYA")

    lualib:Map_GenMonster(map,monsters[monster_name][3],monsters[monster_name][4],3,1,monster_name,1,false)
    --lualib:SysMsg_SendBroadcastMsg("添加"..tostring(monster_name), "AYA")
    return ""
end