---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2020/3/4 14:26
---
local zlsj = {
    10*60*60,
    24*60*60,
    5*24*60
}
function on_create(npc)
    lualib:AddTimer(npc, 999, 1000, -1, "on_timer_talk")
end

function on_timer_talk(npc)

    lualib:SysMsg_SendRoleTalk(npc, "尊敬的玩家你好，这里是智能反外挂系统，谢谢合作")
end



function main(npc, player)
    if lualib:GetInt(player,"gjysj")==0 then
        lualib:SetInt(player,"gjysj",lualib:GetAllTime())
    end
    local cs = lualib:GetWeekInt(player,"zlcs")
    local sttime=lualib:GetAllTime()-lualib:GetInt(player,"gjysj")

    local msg = "#OFFSET<X:0,Y:20>#                           #COLORCOLOR_YELLOW#智能查外挂系统#COLOREND#\n"
    msg = msg.."#OFFSET<X:15,Y:0>#尊敬的玩家你好，这里是智能反外挂系统，谢谢合作\n"
    msg = msg.."#OFFSET<X:15,Y:0>#每人每周可3次免费直接出去\n"
    msg = msg.."#OFFSET<X:15,Y:0>#第四次呆满10小时，第五次1天，第六次封号5天\n"
    msg = msg.."#OFFSET<X:15,Y:0>##COLORCOLOR_BROWN#你已进入次数："..cs.."#COLOREND#\n"
    if cs < 4 then
        msg = msg.."                           <@jinru *01* 我要出去>\n"
    else
        local levelTime = zlsj[cs-3]-sttime
        if levelTime > 0 then
            msg = msg.."            <@jinru *01* 我要出去>"
            msg = msg.."                <@goumai *01* 购买离开>\n"
            msg = msg.."#OFFSET<X:15,Y:0>#您还有:#COLORCOLOR_YELLOW#"..(levelTime).."#COLOREND#秒可以出去\n"
            msg = msg.."#OFFSET<X:15,Y:0>##COLORCOLOR_YELLOW#购买离开每次需要 5000元宝,请考虑清楚再点击购买#COLOREND#\n"
        else
            msg = msg.."                           <@jinru *01* 我要出去>\n"
        end

    end

    lualib:SetPanelSize(npc, 420, 200)
    return msg
end

function jinru(npc, player)
    local cs = lualib:GetWeekInt(player,"zlcs")
    if lualib:GetInt(player,"gjysj")==0 then
        lualib:SetInt(player,"gjysj",lualib:GetAllTime())
    end

    local sttime=lualib:GetAllTime()-lualib:GetInt(player,"gjysj")
    if cs <= 3 then
        lualib:Player_MapMoveXY(player, "龙城", 298, 363, 0)
        return ""
    end
    if sttime >= zlsj[cs - 3] then
        lualib:Player_MapMoveXY(player, "龙城", 298, 363, 0)
        return ""
    else
        lualib:MsgBox(player,"你还没有到出狱时间!")
    end
    return ""
end

function goumai(npc,player)
    lualib:SetInt(player,"gmlk",1)
    lualib:SysMsg_SendBroadcastMsg(tostring(lualib:GetInt(player,"gmlk")),"xiaoheiwu" )
    if not  lualib:Player_SubIngot(player,5000,false,"购买出狱次数","小黑屋管理员") then
        lualib:MsgBox(player,"你的元宝不足!")
        return ""
    end

    lualib:SetWeekInt(player,"zlcs",lualib:GetWeekInt(player,"zlcs") - 1)
    local cishu = lualib:GetWeekInt(player,"zlcs")

    lualib:Player_MapMoveXY(player, "龙城", 298, 363, 0)
    return ""
end