---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2020/3/4 13:42
---
local gb = "一群恶魔的幸运小猪，正在土城四散逃窜!!!"
local a=3600
local b=3600--7200
local ll = math.random(a, b)
local monster_t = {
    [ll] = {--3600秒=1小时  刷新一波以下怪物(不要的可删掉) 无坐标为随机位置
        {"龙城", "真幸运小猪", 10},
        {"龙城", "假幸运小猪", 10},
    },
}

function check()
    for k, v in pairs(monster_t) do
        local id = lualib:GenTimerId("1")
        gen_monster("0", id, k)
        lualib:AddTimerEx("0", id, k * 1000, -1, "gen_monster", tostring(k))
    end
end


function gen_monster(guid, id, index)
    local hour = tonumber(lualib:Time2Str("%H",0))
    if hour >= 14 or hour < 22 then--14:00—22:00

    end
    local index = tonumber(index)
    for _, v in ipairs(monster_t[index]) do
        local key = v[2]
        local max = v[3]
        local map = lualib:Map_GetMapGuid(v[1])
        if map ~= "" then
            local count = lualib:Map_GetMonsterCount(map, key, true, true)
            if count > 0 then
                lualib:Map_RemoveMonster(map, key)
            end
            if max - count > 0 then
                lualib:SysMsg_SendCenterMsg(1, gb,"")
                ll = math.random(a, b)
                for i = 1, (max - count) do
                    if v.x ~= nil and v.y ~= nil then
                        lualib:Map_GenMonster(map, v.x, v.y, 1, 4, key, 1, false)
                    else
                        lualib:Map_BatchGenMonster(map, key, 1, false)
                    end
                end
            end
        end
    end
end