---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2020/3/6 13:15
---
local lua_path = lualib:IO_GetLuaPath()
local package_path = package.path
package.path = string.format("%s;%s?.lua;%s?", package_path, lua_path, lua_path)
require("system/serializer")

function main(player)
    local data = ""
    lualib:ShowFormWithContent(player,"form文件表单","手机测试特效")
    lualib:ShowFormWithContent(player,"脚本表单",data)
    return ""
end