---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2020/3/2 12:36
---

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2019/12/6 16:58
---
local lua_path = lualib:IO_GetLuaPath()
local package_path = package.path
package.path = string.format("%s;%s?.lua;%s?", package_path, lua_path, lua_path)
require("system/serializer")
require("system/timecount_def")

lualib:SetFormAllowFunc({"main","mai","Cishu","uqdd","gengxin","Lingqu","Lfte_dianji"});

local lfte_tb = {
    {
        item_n = "小喇叭", --道具
        leixing = 1, --类型1:物品,2:元宝
        shu = {2,2}, --数量,类型为2时,此项为奖励池的百分比
        jilv = 12,
    },

    {
        item_n = "绑钱袋(30万)", --道具
        leixing = 1, --类型1:物品,2:元宝
        shu = {1,5}, --数量,类型为2时,此项为奖励池的百分比
        jilv = 5,
    },
    {
        item_n = "1级玉佩", --道具
        leixing = 1, --类型1:物品,2:元宝
        shu = {1,10}, --数量,类型为2时,此项为奖励池的百分比
        jilv = 1,
    },
    {
        item_n = "积分券50", --道具
        leixing = 1, --类型1:物品,2:元宝
        shu = {1,1}, --数量,奖励池的百分比
        jilv = 1,
    },
    {
        item_n = "储存箱(10格)", --道具
        leixing = 1, --类型1:物品,2:元宝
        shu = {1,1}, --数量,类型为2时,此项为奖励池的百分比
        jilv = 3,
    },
    {
        item_n = "奖池30%元宝", --道具
        leixing = 2, --类型1:物品,2:元宝
        shu = {1,30}, --数量,类型为2时,此项为奖励池的百分比
        jilv = 2,
    },
    {
        item_n = "金条", --道具
        leixing = 1, --类型1:物品,2:元宝
        shu = {1,1}, --数量,类型为2时,此项为奖励池的百分比
        jilv = 2,
    },
    {
        item_n = "积分券10", --道具
        leixing = 1, --类型1:物品,2:元宝
        shu = {1,1}, --数量,类型为2时,此项为奖励池的百分比
        jilv = 5,
    },
    {
        item_n = "绑钱袋(88万)", --道具
        leixing = 1, --类型1:物品,2:元宝
        shu = {1,1}, --数量,类型为2时,此项为奖励池的百分比
        jilv = 11,
    },
    {
        item_n = "充值卡10元", --道具
        leixing = 1, --类型1:物品,2:元宝
        shu = {1,1}, --数量,类型为2时,此项为奖励池的百分比
        jilv = 3,
    },
    {
        item_n = "黄金虎符", --道具
        leixing = 1, --类型1:物品,2:元宝
        shu = {1,1}, --数量,类型为2时,此项为奖励池的百分比
        jilv = 11,
    },
    {
        item_n = "包裹(20格)", --道具
        leixing = 1, --类型1:物品,2:元宝
        shu = {1,1}, --数量,类型为2时,此项为奖励池的百分比
        jilv = 2,
    },
    {
        item_n = "可口西瓜", --道具
        leixing = 1, --类型1:物品,2:元宝
        shu = {3,10}, --数量,类型为2时,此项为奖励池的百分比
        jilv = 5,
    },
    {
        item_n = "节日活动礼盒", --道具
        leixing = 1, --类型1:物品,2:元宝
        shu = {1,1}, --数量,类型为2时,此项为奖励池的百分比
        jilv = 1,
    },
    {
        item_n = "绑钱袋(66万)", --道具
        leixing = 1, --类型1:物品,2:元宝
        shu = {1,1}, --数量,类型为2时,此项为奖励池的百分比
        jilv = 2,
    },
    {
        item_n = "幻境卷轴", --道具
        leixing = 1, --类型1:物品,2:元宝
        shu = {3,1}, --数量,类型为2时,此项为奖励池的百分比
        jilv = 12,
    },
    {
        item_n = "奖池50%元宝", --道具
        leixing = 2, --类型1:物品,2:元宝
        shu = {1,50}, --数量,类型为2时,此项为奖励池的百分比
        jilv = 1,
    },
    {
        item_n = "行会资源包(大)", --道具
        leixing = 1, --类型1:物品,2:元宝
        shu = {1,1}, --数量,类型为2时,此项为奖励池的百分比
        jilv = 5,
    },


}

local uqdd_tb = {
    {
        ci = 88,--领取次数
        item = {"疾风", 1},
    },

    {
        ci = 188,--领取次数
        item = {"九尾冰狐", 1},
    },

    {
        ci = 1888,--领取次数
        item = {"大角羊", 1},
    },

    {
        ci = 3888,--领取次数
        item = {"绝影豹", 1},
    },


}

local item_name = {"GM刀", 1, 500}--抽奖需要的道具,数量,单张价格
local chou_yb = 100--奖池增加的元宝
local Lfte_shijian = 30*24*60*60 --转盘开启时间，单位秒

local jieshao = [[
#COLOREND##COLORCOLOR_SKYBLUE#1.抽奖一次需要500元宝,每抽奖一次.奖池里就会多100元宝\n2.抽奖活动新区开放一个月.等待下一次抽奖活动开放.抽奖活动里面奖品也同时更新#COLOREND#
]]

function mai(player, num)
    local num = tonumber(num)
    local yb = item_name[3] * num
    if lualib:SubIngot(player, yb, "购买转盘道具", player) then
        lualib:AddItem(player, item_name[1], num, false, "购买转盘道具", player)

    else
        lualib:MsgBox(player, "元宝不足!!")
    end

    return ""
end
--[[加在系统脚本on_system_start()里
if not lualib:HasTimer("0", 20170711) then
	lualib:AddTimer("0", 20170711, 1000, -1, "转盘系统:Lfte_cz")
end
--]]
function Lfte_xianshi(player)
    --ShowTimeCount2(player, 0, 1800200028, "转盘系统", 0, "") --图标
    AddSEIcon(player, 1.2, 0, "转盘系统", 1906100049, "倒计时", "main", "转盘系统", "转盘系统")
    AddIconMagic(player, "转盘系统", 1094200000, -6, -6, 150)

    --AddSEIcon(player, 1, -4, "转盘系统", 1800200028, "倒计时", "main", "转盘系统", "转盘系统")

    --AddIconMagic(player, "转盘系统", 1094000000, -6, -6, 150)

end



-------------------图标被点击-----------------------
function Lfte_dianji(player)
    --ShowTimeCount2(player, 0, 1800200028, "转盘系统", 0, "") --图标
    Lfte(player)
    return ""
end


function Lfte(player)
    local player_tb = lualib:GetDBStr("转盘中奖信息")
    if player_tb == "" then
        player_tb = {}
    else
        player_tb = deserialize(player_tb)
    end


    for i = 1,#uqdd_tb do
        uqdd_tb[i].l = lualib:GetInt(player, "转盘次数领取"..i)
    end
    local tb = [[
	myif_Lfte.tb = ]]..serialize(lfte_tb)..[[
	myif_Lfte.yb = ]]..lualib:GetDBNum("转盘奖励池")..[[
	myif_Lfte.cs = ]]..lualib:GetInt(player, "转盘次数")..[[
	myif_Lfte.sj = ]]..lualib:GetDBNum("转盘剩余时间")..[[
	myif_Lfte.js = ]]..serialize(jieshao)..[[
	myif_Lfte.zjbiao = ]]..serialize(player_tb)..[[
	myif_Lfte.jlb = ]]..serialize(uqdd_tb)..[[

	]]
    lualib:SetStr(player, "转盘状态", "关闭")
    lualib:SetInt(player, "转盘剩余次数", 0)
    lualib:ShowFormWithContent(player, "form文件表单", "转盘系统")
    lualib:ShowFormWithContent(player, "脚本表单", tb)
    return ""
end

function Cishu(player, num)

    if lualib:GetDBNum("转盘剩余时间") < 1 then
        lualib:MsgBox(player, "活动尚未开启！请等待下一次开启！！")
        return ""
    end
    local cishu = tonumber(num)
    if not lualib:Player_IsIngotEnough(player, item_name[3] * cishu, false) then
        lualib:MsgBox(player, "元宝不足!!!")
        return ""
    end
    lualib:SetInt(player, "转盘剩余次数", cishu)
    if not lualib:HasTimer(player, 2017711) then
        lualib:AddTimer(player, 2017711, 500, -1, "Gavc")
    end
    return ""
end

function Gavc(player)
    local suiji_zongzhi = 0  --随机总值
    local suiji = 0 --随机值
    local cishu = lualib:GetInt(player, "转盘剩余次数")
    if cishu <= 0 then
        if lualib:HasTimer(player, 2017711) then
            lualib:DisableTimer(player, 2017711)
        end
        return ""
    end

    if cishu > 0 and lualib:GetStr(player, "转盘状态") == "关闭" then
        lualib:SetStr(player, "转盘状态", "开启")
        lualib:ShowFormWithContent(player, "脚本表单", "myif_Lfte.zhuan()")
        --首先获得随机总值
        for k,v in pairs(lfte_tb) do
            suiji_zongzhi = suiji_zongzhi + v.jilv
        end


        suiji = math.random(suiji_zongzhi) --获得随机值
        local suiji_1 = 0
        --开始遍历随机值对应哪个物品
        for k,v in pairs(lfte_tb) do
            local suiji_2 = suiji_1 + v.jilv
            if suiji >= suiji_1 and  suiji < suiji_2 then
                lualib:SetInt(player,"zhongjiangshuzi",k)
                lualib:ShowFormWithContent(player, "脚本表单", "myif_Lfte.zhong = "..k)
                break
            else
                suiji_1 = suiji_1 + v.jilv
            end
        end
        lualib:SetInt(player, "转盘剩余次数", cishu - 1)
    end


    return ""
end

function uqdd(player)
    local lv = lualib:GetInt(player,"zhongjiangshuzi")
    local v = lfte_tb[lv]

    if not lualib:Player_SubIngot(player, item_name[3], false, "转盘", "转盘") then --失败关闭窗口
        lualib:ShowFormWithContent(player, "脚本表单", "myif_Lfte.Gb()")
        return ""
    end

    lualib:SetDBNumEx("转盘奖励池", math.floor(lualib:GetDBNum("转盘奖励池")+chou_yb), 3)     --增加奖次
    if v.leixing == 2 then
        local yb = lualib:GetDBNum("转盘奖励池") * (v.shu[2]/100)
        if not lualib:Player_AddIngot(player, yb, false, "转盘系统奖励", player) then
            lualib:MsgBox(player, "应奖励元宝"..yb.."失败!请截图给管理补偿!!")
            return ""
        end
        lualib:SetDBNumEx("转盘奖励池", math.floor(lualib:GetDBNum("转盘奖励池")-yb), 3)

    else
        local shu = v.shu[1]
        if lualib:BagFree(player, true, false, false) < shu then
            lualib:Mail("转盘系统奖励", lualib:Name(player), "转盘系统奖励.", 0, 0, {v.item_n, shu, 0})
        else
            lualib:AddItem(player, v.item_n, shu, false, "转盘系统奖励", player)
            local name = lualib:Name(player)
            if v.jilv < 5 then
                local s = "玩家【"..name.."】通过转盘抽取到["..v.item_n.."]！"
                lualib:SysMsg_SendBroadcastColor(s, "", 1, 12)
            end
        end
    end

    lualib:SetInt(player, "转盘次数", lualib:GetInt(player, "转盘次数") + 1)

    local player_tb = lualib:GetDBStr("转盘中奖信息")

    if player_tb == "" then
        player_tb = {}
    else
        player_tb = deserialize(player_tb)
    end
    local p_name = lualib:Name(player)
    local a = lualib:GetAllTime()
    local timeStr = lualib:Time2Str("%H:%M:%S", a)
    local n = {timeStr, p_name, v.item_n}
    table.insert(player_tb, 1, n)

    if #player_tb > 50 then
        table.remove(player_tb,50)
    end
    lualib:SetDBStrEx("转盘中奖信息", serialize(player_tb),6)
    lualib:SetStr(player, "转盘状态", "关闭")
    local player_tb = lualib:GetDBStr("转盘中奖信息")

    if player_tb == "" then
        player_tb = {}
    else
        player_tb = deserialize(player_tb)
    end

    for i = 1,#uqdd_tb do
        uqdd_tb[i].l = lualib:GetInt(player, "转盘次数领取"..i)
    end
    local tb = [[
	myif_Lfte.tb = ]]..serialize(lfte_tb)..[[
	myif_Lfte.yb = ]]..lualib:GetDBNum("转盘奖励池")..[[
	myif_Lfte.cs = ]]..lualib:GetInt(player, "转盘次数")..[[
	myif_Lfte.sj = ]]..lualib:GetDBNum("转盘剩余时间")..[[
	myif_Lfte.js = ]]..serialize(jieshao)..[[
	myif_Lfte.zjbiao = ]]..serialize(player_tb)..[[
	myif_Lfte.jlb = ]]..serialize(uqdd_tb)..[[
	]]

    lualib:ShowFormWithContent(player, "脚本表单", tb)
    lualib:ShowFormWithContent(player, "脚本表单", "myif_Lfte.gx()")
    return ""
end

function Lfte_cz()
    if lualib:GetDBNum("转盘重置") == 0 then
        lualib:SetDBNum("转盘重置", 1)
        lualib:SetDBNum("转盘轮次",lualib:GetDBNum("转盘轮次")+1)
        lualib:SetDBNum("转盘奖励池",0)
        lualib:SetDBNum("转盘剩余时间", Lfte_shijian)
    end
    lualib:GSRunScript("gengxin", "")
    if lualib:GetDBNum("转盘剩余时间") > 0 then
        lualib:SetDBNum("转盘剩余时间", lualib:GetDBNum("转盘剩余时间") - 1)
    end
end

function gengxin(player)
    if lualib:GetDBNum("转盘轮次") ~= lualib:GetInt(player, "转盘轮次个人") then
        lualib:SetInt(player, "转盘次数", 0)
        lualib:SetInt(player, "转盘轮次个人", lualib:GetDBNum("转盘轮次"))
        for i = 1,4 do
            lualib:SetInt(player, "转盘次数领取"..i, 0)
        end
    end

    for i = 1,#uqdd_tb do
        uqdd_tb[i].l = lualib:GetInt(player, "转盘次数领取"..i)
    end
    local tb = [[
	myif_Lfte.yb = ]]..lualib:GetDBNum("转盘奖励池")..[[
	myif_Lfte.cs = ]]..lualib:GetInt(player, "转盘次数")..[[
	myif_Lfte.sj = ]]..lualib:GetDBNum("转盘剩余时间")..[[
	myif_Lfte.jlb = ]]..serialize(uqdd_tb)..[[
	]]
    lualib:ShowFormWithContent(player, "脚本表单", tb)
    lualib:ShowFormWithContent(player, "脚本表单", "myif_Lfte.gx()")
    return ""
end


function Lingqu(player, lv)
    local lv = tonumber(lv)

    if lualib:GetInt(player, "转盘次数领取"..lv) > 0 then
        lualib:MsgBox(player, "该奖励已领取过了！！")
        return ""
    end

    if lualib:GetInt(player, "转盘次数") < uqdd_tb[lv].ci then
        lualib:MsgBox(player, "未达领取要求！！")
        return ""
    end

    if not lualib:AddItem(player, uqdd_tb[lv].item[1], uqdd_tb[lv].item[2], false, "转盘次数领取", player) then
        lualib:MsgBox(player, "领取失败！！")
        return ""
    end


    lualib:SetInt(player, "转盘次数领取"..lv, 1)
    return ""
end


