---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2020/3/14 13:03
---
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 16017.
--- DateTime: 2020/1/8 14:40
---
function main(npc, player)
    local msg = "#COLORCOLOR_COLD#<@openWindow *01*打开选择窗口>     <@aaa *01*加>  <@bbb *03*获得宠物>  <@ccc *03*洪大吊>#COLOREND#\n"
    msg = msg .. "#COLORCOLOR_COLD#<@testEffects *01*测试手机特效>#COLOREND#"
    return msg
end

function openWindow(npc, player)
    lualib:DelayCall(player, 1, "warGodForm:openUI", "")

    return ""
end

function aaa(npc,player)
    local map = lualib:MapGuid(player)
    local ranges = {0, 0, 0, 1500, 1500}
    local tb_1 = lualib:Map_GetRegionMonstersEx(map,"",ranges,true,true)
    for i,v in pairs(tb_1) do
        lualib:SetHp(v, 20000000, true)
        lualib:SendRoleHPNtf(player)
        lualib:SysMsg_SendBroadcastMsg(tostring(lualib:Name(v)), "")

    end

    return ""
end

function bbb(npc, player)
    lualib:Player_Summon(player, "熊猫宝宝", 100)
    return ""
end

function ccc(npc,player)
    local bb = lualib:Player_Summon(player, "洪大吊", 7)
    if bb ~= nil then
        lualib:AddSkill(bb,"如来神掌")
        lualib:Monster_AddSkillData(bb,480,80)
    end

    return ""
end

function testEffects(npc,player)
    lualib:DelayCall(player,1,"手机测试特效:main","")
end