---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2020/3/11 12:58
---

local fb_tbl = {"一号副本","二号副本","三号副本","四号副本","五号副本"}
local npc_tbl = {
    ["生死副本一层"] = {"生死副本传送员",30,23,0},
    ["生死副本二层"] = {"生死副本传送员",14,58,0},
    ["生死副本三层"] = {"生死副本传送员",49,28,0},

}
function on_create(npc)
    for i = 1,#fb_tbl do
        lualib:SetDBStr(fb_tbl[i],"")
    end
end


function main(npc, player)
    local fb = {}
    for i = 1,#fb_tbl do
        local shuju = lualib:GetDBStr(fb_tbl[i])
        if shuju == "" then
            fb[i] = {}
            fb[i].name = fb_tbl[i]
            fb[i].pname = "暂无人挑战"
            fb[i].plv = 0
            fb[i].py = 0
            fb[i].times = 0
        else
            fb[i] = json.decode(shuju)
        end
    end

    local msg = [[\n#COLORCOLOR_GRAY#  ---------------------------------------------------------------#COLOREND#
#COLORCOLOR_SKYBLUE#  副本类型#COLOREND#  #COLORCOLOR_BLUE#副本带队人#COLOREND#      #COLORCOLOR_YELLOW#队长等级#COLOREND#  #COLORCOLOR_BLUE#组队人数#COLOREND#   #COLORCOLOR_PURPLE#任务剩余时间#COLOREND#
#COLORCOLOR_GRAY#  ---------------------------------------------------------------#COLOREND#
]]
    local times = 0
    for i = 1,#fb do
        if fb[i].times == 0 then
            times = "未开启"
        else
            times = lualib:GetInt(lualib:Name2Guid(fb[i].pname),"guizu").."分钟"
        end
        for i1 = string.len(fb[i].pname),13 do
            fb[i].pname = fb[i].pname.." "
        end
        for i2 = string.len(fb[i].plv),2 do
            fb[i].plv = " "..fb[i].plv
        end
        msg = msg.."  #COLORCOLOR_YELLOW#"..fb[i].name.."#COLOREND#  #COLORCOLOR_BLUE#"..fb[i].pname.."#COLOREND#   Lv #COLORCOLOR_PURPLE#"..fb[i].plv.."#COLOREND#       #COLORCOLOR_GREENG#"..fb[i].py.."#COLOREND#     倒计时：#COLORCOLOR_SKYBLUE#"..times.."#COLOREND#\n"
    end
    msg = msg..[[
#COLORCOLOR_GRAY#  ---------------------------------------------------------------#COLOREND#
#COLORCOLOR_BLUE#  1、击杀生死副本一层的#COLOREND# #COLORCOLOR_YELLOW#生死红猪#COLOREND# #COLORCOLOR_RED#15只#COLOREND# #COLORCOLOR_YELLOW#生死黑猪#COLOREND# #COLORCOLOR_RED#15只#COLOREND#
#COLORCOLOR_BLUE#  2、击杀生死副本二层的#COLOREND# #COLORCOLOR_YELLOW#生死白猪 #COLOREND##COLORCOLOR_RED#15只#COLOREND#
#COLORCOLOR_BLUE#  3、击杀生死副本三层的#COLOREND# #COLORCOLOR_YELLOW#生死战将#COLOREND# #COLORCOLOR_RED#5只#COLOREND# #COLORCOLOR_YELLOW#生死巨蛾#COLOREND# #COLORCOLOR_RED#5只#COLOREND# #COLORCOLOR_YELLOW#生死教主#COLOREND# #COLORCOLOR_RED#1只#COLOREND#
#COLORCOLOR_BLUE#  4、任务完成后队长可领取#COLOREND##COLORCOLOR_RED#生死宝盒一个#COLOREND#
#COLORCOLOR_BLUE#  5、每天每人可以进入生死副本1次，每次进入需要1个#COLOREND##COLORCOLOR_YELLOW#黄金虎符#COLOREND#
#COLORCOLOR_BLUE#  6、必须3人以上组队模式并且队员达到#COLORCOLOR_RED#35级以上#COLOREND##COLORCOLOR_BLUE#可进入。#COLOREND#
#COLORCOLOR_BLUE#  7、“生死副本”在任务过程中，#COLOREND##COLORCOLOR_RED#队长或者队员离开地图或死亡，\n   都将判定挑战失败！#COLOREND#
#COLORCOLOR_BLUE#  8、副本最多可同时接受5支队伍挑战，每支队伍限制#COLORCOLOR_RED#60分钟#COLOREND##COLORCOLOR_BLUE#完成！#COLOREND#
#COLORCOLOR_BLUE#  9、副本怪物拥有#COLORCOLOR_RED#10倍巨额经验值。#COLOREND##COLORCOLOR_BLUE#并且也是#COLORCOLOR_RED#宝石爆率所在地！#COLOREND#
#COLORCOLOR_GRAY#  ---------------------------------------------------------------#COLOREND#
            <@挑战副本 *01*√ ·挑战副本>       #COLORCOLOR_PURPLE#今日挑战次数：]]..lualib:GetDayInt(player,"生死副本次数")..[[/1次#COLOREND# \n           注：#COLORCOLOR_RED#产出的宝石可以去宝石商人处合成所需宝石#COLOREND#]]

    local msg2 = [[#COLORCOLOR_SKYBLUE#副本类型#COLOREND#  #COLORCOLOR_BLUE#副本带队人#COLOREND# #COLORCOLOR_YELLOW#队长等级#COLOREND#  #COLORCOLOR_BLUE#组队人数#COLOREND#   #COLORCOLOR_PURPLE#任务剩余时间#COLOREND#
#COLORCOLOR_GRAY#--------------------------------------------------#COLOREND#
]]

    local times = 0
    for i = 1,#fb do
        if fb[i].times == 0 then
            times = "未开启"
        else
            times = lualib:GetInt(lualib:Name2Guid(fb[i].pname),"guizu").."分钟"
        end
        for i1 = string.len(fb[i].pname),13 do
            fb[i].pname = fb[i].pname.." "
        end
        for i2 = string.len(fb[i].plv),2 do
            fb[i].plv = " "..fb[i].plv
        end
        msg2 = msg2.."#COLORCOLOR_YELLOW#"..fb[i].name.."#COLOREND#  #COLORCOLOR_BLUE#"..fb[i].pname.."#COLOREND# Lv #COLORCOLOR_PURPLE#"..fb[i].plv.."#COLOREND#  #COLORCOLOR_GREENG#"..fb[i].py.."#COLOREND# 倒计时：#COLORCOLOR_SKYBLUE#"..times.."#COLOREND#\n"
    end
    msg2 = msg2..[[#COLORCOLOR_GRAY#--------------------------------------------------#COLOREND#]]

    msg2 = msg2.."                              <@mainTalkForMobile2 *03*√ ·下一页>"


    if lualib:GetClientType(player) == 0 then
        lualib:NPCTalkDetailEx(npc, player, msg, 450, 410)
    elseif lualib:GetClientType(player) == 2 then
        lualib:NPCTalkDetailEx(npc, player, msg2, 500, 410)
    else
        lualib:SysMsg_SendWarnMsg(player,"客户端错误")
    end
    return""


end

function mainTalkForMobile2(npc,player)
    local msg2 = ""
    msg2 = msg2..[[
#COLORCOLOR_GRAY#--------------------------------------------------#COLOREND#
#COLORCOLOR_BLUE#1、击杀生死副本一层的#COLOREND# #COLORCOLOR_YELLOW#生死红猪#COLOREND# #COLORCOLOR_RED#15只#COLOREND# #COLORCOLOR_YELLOW#生死黑猪#COLOREND# #COLORCOLOR_RED#15只#COLOREND#
#COLORCOLOR_BLUE#2、击杀生死副本二层的#COLOREND# #COLORCOLOR_YELLOW#生死白猪 #COLOREND##COLORCOLOR_RED#15只#COLOREND#
#COLORCOLOR_BLUE#3、击杀生死副本三层的#COLOREND# #COLORCOLOR_YELLOW#生死战将#COLOREND# #COLORCOLOR_RED#5只#COLOREND# #COLORCOLOR_YELLOW#生死巨蛾#COLOREND# #COLORCOLOR_RED#5只#COLOREND# #COLORCOLOR_YELLOW#生死教主#COLOREND# #COLORCOLOR_RED#1只#COLOREND#
#COLORCOLOR_BLUE#4、任务完成后队长可领取#COLOREND##COLORCOLOR_RED#生死宝盒一个#COLOREND#
#COLORCOLOR_BLUE#5、每天每人可以进入生死副本1次，每次进入需要1个#COLOREND##COLORCOLOR_YELLOW#黄金虎符#COLOREND#
#COLORCOLOR_BLUE#6、必须3人以上组队模式并且队员达到#COLORCOLOR_RED#35级以上#COLOREND##COLORCOLOR_BLUE#可进入。#COLOREND#\n]]
    msg2 = msg2.."<@main *03*√ ·上一页>                   <@mainTalkForMobile3 *03*√ ·下一页>"
    return msg2
end

function mainTalkForMobile3(npc,player)
    local msg2 = ""
    msg2 = msg2..[[
#COLORCOLOR_GRAY#--------------------------------------------------#COLOREND#
#COLORCOLOR_BLUE#7、“生死副本”在任务过程中，#COLOREND##COLORCOLOR_RED#队长或者队员离开地图或者死亡，都将判定挑战失败！#COLOREND#
#COLORCOLOR_BLUE#8、副本最多可同时接受5支队伍挑战副本，每支队伍限制#COLORCOLOR_RED#60分钟#COLOREND##COLORCOLOR_BLUE#内完成任务！#COLOREND#
#COLORCOLOR_BLUE#9、副本怪物拥有#COLORCOLOR_RED#10倍巨额经验值。#COLOREND##COLORCOLOR_BLUE#并且也是#COLORCOLOR_RED#宝石爆率所在地！#COLOREND#
#COLORCOLOR_GRAY#--------------------------------------------------#COLOREND#
<@挑战副本 *01*√ ·挑战副本> #COLORCOLOR_PURPLE#今日挑战次数：]]..lualib:GetDayInt(player,"生死副本次数")..[[/1次#COLOREND# <@mainTalkForMobile2 *03*√ ·上一页> \n注：#COLORCOLOR_RED#产出的宝石可以去宝石商人处合成所需宝石#COLOREND#\n]]

    return msg2
end



function 挑战副本(npc,player)
    local fb = {}
    local id = 0
    for i = 1,#fb_tbl do
        if lualib:GetDBStr(fb_tbl[i]) == "" then
            id = i
            break
        end
    end

    if id == 0 then
        return "没有空余副本可进入，请等待。"
    end
    local item_name = "黄金虎符"

    fb.name = fb_tbl[id]
    fb.pname = lualib:Name(player)
    fb.plv = lualib:Level(player)
    local dynum = 1
    if not lualib:Player_HasTeam(player) then
        return "未组队无法进入生死副本"
    else
        if not lualib:Player_IsTeamLeader(player) then
            return "你不是队长，无法进入。"
        end
        dynum = lualib:Player_GetTeamList(player)
        if #dynum < 3 then
            return "队伍人数少于3人，无法进入！"
        end
        for i = 1,#dynum do
            if lualib:Level(dynum[i]) < 35 then
                return "队友："..lualib:Name(dynum[i]).." 等级低于35级,无法进入副本！"
            end
            if lualib:ItemCount(dynum[i],item_name) < 1 then
                return "队友："..lualib:Name(dynum[i]).."没有道具："..item_name.." 无法进入！"
            end
            if lualib:GetDayInt(dynum[i],"生死副本次数") > 0 then
                return "队友："..lualib:Name(dynum[i]).." 今日已经进入一次副本，无法进入！"
            end
            if lualib:Distance(npc,dynum[i]) >= 8 then
                return "队友："..lualib:Name(dynum[i]).." 距离NPC太远，无法进入副本！"
            end
            if lualib:MapGuid(npc) ~= lualib:MapGuid(dynum[i]) then
                return "队友："..lualib:Name(dynum[i]).." 距离NPC太远，无法进入副本！"
            end
        end


        local fbid = lualib:Map_CreateDgn("生死副本一层",true,3600)
        for i = 1,#dynum do
            if not lualib:DelItem(dynum[i],item_name,1,2,"进入生死副本","") then
                return "队友："..lualib:Name(dynum[i]).."没有道具："..item_name.." 无法进入！"
            end
            lualib:Player_SetDgnTicket(dynum[i],fbid)
            lualib:SetInt(dynum[i],"生死副本标志",0)
            lualib:Player_EnterDgn(dynum[i],"生死副本一层",84,84,3)
            lualib:SetStr(dynum[i],"生死副本id",fb_tbl[id])
            lualib:SetDayInt(dynum[i],"生死副本次数",lualib:GetDayInt(dynum[i],"生死副本次数") + 1)
            if lualib:HasTimer(dynum[i],800) then
                lualib:DisableTimer(dynum[i],800)
            end
            lualib:SetInt(dynum[i],"guizu",60)
            lualib:AddTimerEx(dynum[i],800,60000,60,"生死副本定时器",dynum[i])
            lualib:AddTimer(dynum[i],900,1000,-1,"队伍判断")
        end
        fb.py = #dynum
    end

    if lualib:GetInt(player,"生死副本任务") == 0 then
        lualib:SetInt(player,"生死副本任务",1)
        lualib:SysMsg_SendBoardMsg(player, "[英雄成就]", "恭喜你达成了【生死副本任务】成就，可前往领取奖励！", 1500)
    end
    fb.times = lualib:GetAllTime()
    lualib:SetDBStr(fb_tbl[id],json.encode(fb))
    lualib:SysMsg_SendBroadcastMsg("队长【"..lualib:Name(player).."】带领队伍"..(#dynum).."人，进入了生死副本地图，祝他通关获得巨额经验吧","系统消息")

    return ""
end




function 生死副本定时器(player)
    local map_keyname = {
        ["生死副本一层"] = "",
        ["生死副本二层"] = "",
        ["生死副本三层"] = "",
    }
    local player_mapkeyname = lualib:KeyName(lualib:MapGuid(player))
    if map_keyname[player_mapkeyname] ~= nil then
        lualib:SetInt(player,"guizu", lualib:GetInt(player,"guizu") - 1)
        lualib:SysMsg_SendPromptMsg(player,"您当前在地图剩余时间为"..lualib:GetInt(player,"guizu").."分钟")
        if player_mapkeyname ~= "生死副本三层" then
            lualib:SysMsg_SendPromptMsg(player,"在击杀完当前地图所有怪物后，可前往("..tostring(npc_tbl[player_mapkeyname][2])..","..tostring(npc_tbl[player_mapkeyname][3])..")寻找生死副本传送员进入下一层")
        else
            lualib:SysMsg_SendPromptMsg(player,"在击杀完当前地图所有怪物后，可前往"..npc_tbl[player_mapkeyname][1].."("..tostring(npc_tbl[player_mapkeyname][2])..","..tostring(npc_tbl[player_mapkeyname][3])..")领取奖励")
        end
        if lualib:GetInt(player,"guizu") <= 0 then
            lualib:SetDBStr(lualib:GetStr(player,"生死副本id"),"")
            lualib:Player_MapMoveXY(player,"巫山城",378,282,3)
            lualib:DisableTimer(player,800)
        end
    else
        --[[lualib:Player_MapMoveXY(player,"龙城",265,265,3)--]]
        lualib:DisableTimer(player,800)
    end
end

function 队伍判断(player)
    if not lualib:Player_HasTeam(player) then
        local players = lualib:Map_GetMapPlayers(lualib:MapGuid(player),false)
        for i, v in pairs(players) do
            lualib:SetInt(v,"guizu",0)
            lualib:SetDBStr(lualib:GetStr(v,"生死副本id"),"")
            lualib:DisableTimer(v,800)
            lualib:MsgBox(v,"队友离开地图或者死亡，副本结束！")
            lualib:DisableTimer(v,900)
        end
        lualib:Map_DestroyDgn(lualib:MapGuid(player))
    end


end

function 离队回调提示(player)
    if lualib:KeyName(lualib:MapGuid(player)) == "巫山城" then
        lualib:SetDBStr(lualib:GetStr(player,"生死副本id"),"")
        lualib:MsgBox(player,"队友离开地图或者死亡，副本结束！")
    end
end
