---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2020/3/4 16:45
---
local zlsj = {
    0,
    0,
    0,
    10*60*60,
    24*60*60,
    7*24*60*60
}
function on_map_create(map)
    lualib:AddTrigger(map, lua_trigger_enter_map, "on_enter_map")
    lualib:AddTrigger(map, lua_trigger_leave_map , "on_leave_map")
    lualib:AddTrigger(map, lua_trigger_role_pre_harm, "on_pre_harm")
end

function on_leave_map(player)
    if lualib:GetInt(player,"leavePrison") == 1 then
        lualib:SetInt(player,"leavePrison",0)
        return ""
    end
    local sttime=lualib:GetAllTime()-lualib:GetInt(player,"gjysj")
    local cs =  lualib:GetWeekInt(player,"zlcs")
    lualib:SetInt(player, "vertifyCount", 0)
    if sttime < zlsj[cs] then
        lualib:DelayCall(player,1,"back","")
        return ""
    end

    if lualib:GetInt(player,"gmlk") == 1 then
        lualib:DelayCall(player,1,"back","")
        return  ""
    end


end

function on_enter_map(player)
    local lxjy = lualib:GetInt(player,"lxjy")
    local lhdt = lualib:GetInt(player,"lhdt")

    if lxjy == 1 or lhdt == 1 then

        lualib:SetInt(player,"lxjy",0)
        lualib:SetInt(player,"lhdt",0)
    else
        lualib:SetInt(player,"gjysj",lualib:GetAllTime())

        if not lualib:HasTrigger(lualib:MapGuid(player), lua_trigger_role_pre_harm, "on_pre_harm") then
            lualib:AddTrigger(lualib:MapGuid(player), lua_trigger_role_pre_harm, "on_pre_harm")
        end

        lualib:SetWeekInt(player,"zlcs",lualib:GetWeekInt(player,"zlcs") + 1)

        local cs = lualib:GetWeekInt(player,"zlcs")

        if  cs > 5 then
            local name = lualib:Name(player)
            lualib:SetWeekInt(player,"zlcs",0)
            lualib:KickByName(name,2,"超过5次进入监狱，疑似开挂踢下线在封号！")
            lualib:DelayCall(player,3000,"监狱脚本:kickFbd","")
        end
    end
end

function kickFbd(player)
    local name = lualib:Name(player)
    lualib:SetFbdLogin(name,2,zlsj[6],"超过5次进入监狱封号")

    return ""
end

function back(player)

    if lualib:GetInt(player,"gmlk") == 1 then
        lualib:SetInt(player,"gmlk",0)
        return ""
    end

    lualib:SetInt(player,"lhdt",1)           --拉回地图

    lualib:Player_MapMoveXY(player, "监狱", 22, 22, 0)
end

function on_pre_harm(beAttacker, attacker, hp, defenceNum, skillKeyName, isCritical)
    return 0
end