---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2020/2/28 19:04
---

local lua_path = lualib:IO_GetLuaPath()
local package_path = package.path
package.path = string.format("%s;%s?.lua;%s?", package_path, lua_path, lua_path)
require("system/logic_def_lua")

local mapkey = "墓穴组队一"		--组队副本地图索引名

local itemKey = "墓穴组队卷轴"	--组队进入地图需求道具

local ztimesz = 3600			--组队副本存在的时间(单位:秒)

local _ztimesz = 3600	        --组队允许在地图呆多久

---------古墓------------
local require_level = 0	--进入古墓地图等级限制

local require_gold = 0	--进入古墓地图消耗金币


function main(npc,player)
    lualib:SetPanelSize(npc, 420, 210)

    if lualib:Level(player) < 1 then
        return "15级后才可传送至各大地图"
    end

    local msg ="\n  常年看守在此，来来往往的过客见过不少了，可就是没见过你呢。\n  据说虹魔教主藏匿在猪洞七层。\n\n\n\n"
    --msg = msg.."    #IMAGE<ID:1902700019># <@move_srgm *01*骷 髅 洞>　      "
    msg = msg.."   <@move_fqkq *01*了解石墓>　      "
    if lualib:Player_IsGM(player) then
        msg = msg.."   <@callNpc *01*召唤NPC> "

    end

    --msg = msg.."#IMAGE<ID:1902700019># <@move_wmsm *01*沃玛祠庙>　     \n"
    --msg = msg.."    #IMAGE<ID:1902700019># <@move_wgd *01*蜈 蚣 洞>        "
    --msg = msg.."#IMAGE<ID:1902700019># <@move_smrk *01*石  墓>          "
    --msg = msg.."#IMAGE<ID:1902700019># <@move_sm *01*祖犸寺庙>　        \n"
    --msg = msg.."    #IMAGE<ID:1902700019># <@move_fmkq *01*封  魔>  　　　　"
    --msg = msg.."    #IMAGE<ID:1902700019># <@move_clmg *01*白 日 门>        \n\n"
    --msg = msg.."#IMAGE<ID:1902700019># <@hdcc *01*海底沉船>　　　　\n"
    --msg = msg.."    #IMAGE<ID:1902700019># <@fmzd *01*伏魔之地>　　　　"
    --msg = msg.."#IMAGE<ID:1902700019>#<@move_huanj *01* 幻    境>　      \n\n"
    --msg = msg.."#IMAGE<ID:1902700019>#<@move_huanj *01* 幻    境>　      \n"
    --msg = msg.."    #IMAGE<ID:1902700019># <@guomudubao *01*夺宝神殿>　      "
    --msg = msg.."#IMAGE<ID:1902700019># <@xinhuisd *01*行会圣地>　     \n\n"
    --msg = msg.."#IMAGE<ID:1902700019>#<@move_huanj *01* 幻    境>\n\n"
    --msg = msg.."\n\n    #COLORCOLOR_MAGENTA#摆摊提示：达到25级，可在比齐省,龙城安全区,仓库处摆摊#COLOREND#"
    --msg = msg.."                                              #IMAGE<ID:1902700019># <@main *01*返回>\n"
    return msg
end

local Martial = {
    "卸岭门",
    "力士门",
    "寻龙门",
    "摸金门",
    "搬山门",
    "分甲门"
}

local mapName = {
    {"龙城",295,339},
    {"巫山城",376,283},
    {"日月门",198,209},
    {"蛮荒城",198,169},
    {"镇魔城",206,176}
}

function callNpc()
    local mapRandom = lualib:GenRandom(1,#mapName)          --随机地图
    local map = mapName[mapRandom][1]                       --地图名称
    local mapGuid = lualib:Map_GetMapGuid(map)              --地图GUID
    local random = lualib:GenRandom(1,6)                    --随机门派
    lualib:SetDBNum("mapRandom",mapRandom)
    lualib:SetDBNum("mpRandom",random)                --保存随机门派
    lualib:SysMsg_SendBroadcastMsg(tostring(mapRandom)..":"..tostring(map),"门派入侵")
    lualib:SysMsg_SendBroadcastColor(tostring(Martial[random]).."反贼入侵"..tostring(map).."请与"..tostring(Martial[random]).."成员组队前往"..map.."中心100范围内寻找NPC进入!!十分钟后NPC消失","系统公告",1,12)
    lualib:SysMsg_SendBroadcastColor(tostring(Martial[random]).."反贼入侵"..tostring(map).."请与"..tostring(Martial[random]).."成员组队前往"..map.."中心100范围内寻找NPC进入!!十分钟后NPC消失","系统公告",1,12)
    lualib:SysMsg_SendBroadcastColor(tostring(Martial[random]).."反贼入侵"..tostring(map).."请与"..tostring(Martial[random]).."成员组队前往"..map.."中心100范围内寻找NPC进入!!十分钟后NPC消失","系统公告",1,12)

    for i=1,10 do
        if lualib:Map_GenNpc(mapGuid,"门派入侵",mapName[mapRandom][2],mapName[mapRandom][3],100,1) == "" then       --刷新npc
            lualib:SysMsg_SendBroadcastMsg("刷新npc失败", "")
        end
    end
    lualib:AddTimerEx(mapGuid,1008611,1000*60,1,"门派入侵:delNpc","")
    return ""
end

function main_move_city(npc,player)
    local msg = [[
	年轻人，你也和我一样坚信我们终有一天能回家吗？只要有勇气接受挑战，不论兽人还是雪山，都能征服！你想去什么地方接受锤炼呢，我可以送你一程！\n\n]]
    msg = msg.." #IMAGE1902700015# <@MapMoveA#巫山城#336#280 *01*去>比齐\n"
    --msg = msg.." #IMAGE1902700015# <@move_shop *01*去>商店\n"
    msg = msg.." #IMAGE1902700015# <@move_city *01*去>其它地方\n"
    --msg = msg.." #IMAGE1902700015# <@main_zhudui *01*组队除魔>\n"
    --msg = msg.." #IMAGE1902700015# <@guomudubao *01*夺宝神殿>\n\n"
    --msg = msg.." #IMAGE1902700015# <@fire_tm *01*火焰屠魔>\n"
    --msg = msg.." #IMAGE1902700017# <@apperceive *01*洞察魔兽>\n\n"
    --msg = msg.."<@text *01*测试专用>\n"
    msg = msg.." #IMAGE<ID:1902700034># <@exit_e *01*离 开>"
    lualib:SetPanelSize(npc, 400, 205)
    return msg
end

function text(npc, player)
    local mon_k = "进尸王殿僵尸"
    local map = lualib:MapGuid(npc)
    local x, y, r = 245, 269, 5
    lualib:Map_GenSingleMonster(map, x, y, r, lualib:GenRandom(1, 8), mon_k, false)

    return ""
end



function exit_e(npc, player)
    return ""
end
-------行会圣地----------


function xinhuisd(npc,player)
    lualib:SetPanelSize(npc, 400, 200)
    local msg = "这是一块宝地，各大行会首领必争之地，\n"
    msg = msg .. "传说里面灵气十足，对修炼有极大好处，\n"
    msg = msg .. "也传说里面有圣兽，凶猛无比，\n"
    msg = msg .. "总之这也是是非之地，只有有行会的人才可进入。\n\n\n\n\n"
    msg = msg .. "<@jinru *01*进入圣地>\n"
    msg = msg .. "<@hudjs *01*圣地介绍>"
    msg = msg .. ""
    return msg
end

function hudjs(npc,player)
    lualib:SetPanelSize(npc, 400, 200)
    local msg = "每周五20:00开启，开启时间60分钟。\n"
    msg = msg .. "圣地开启5分钟后禁止进入，\n"
    msg = msg .. "圣地内每秒增加100经验，1小时共计360000经验\n"
    msg = msg .. "击杀非本行会成员可为行会获得1点积分，\n"
    msg = msg .. "圣地关闭前积分最高的行会每位成员随机获得2-3点声望，\n"
    msg = msg .. "其他行会成员则获得1点声望，\n"
    msg = msg .. "圣地开启30分钟后将刷新3只圣地教主。"
    return msg
end

function jinru(npc, player)
    lualib:SetPanelSize(npc, 400, 200)
    local player_level = lualib:Level(player)
    if lualib:GetInt("0", "hanghuizhenba_rukou1") ~= 1 then
        return "圣地尚未开启！"
    end
    if player_level < 35 then
        return "需要等级达到35级才能进入。"
    end
    if lualib:GetFamilyName(player) == "" then
        return "需要加入行会才能进入。"
    end

    local dgn = lualib:GetStr("0", "hanghuizhenba_dgn")
    if dgn == "" then
        return "活动地图还没有准备好。"
    end

    if lualib:HasBuff(player,"摆摊") then
        return  "你当前处于摆摊状态，无法传送"
    end

    if lualib:Player_SetDgnTicket(player, dgn) == false then
        return "进入失败！"
    end

    if lualib:Player_EnterDgn(player, lualib:KeyName(dgn), 0, 0, 0) == false then
        return "进入失败！"
    end
    --lualib:SysMsg_SendBroadcastMsg("玩家【"..lualib:Name(player).."】进入了行会争霸地图，大量声望奖励等着他领取！", "系统通知")
    return ""
end



---------古墓------------

function dubaojl(npc,player)
    lualib:SetPanelSize(npc, 400, 200)
    local msg = "开区当天不开放，第二天开放此活动。\n"
    msg = msg .. ""
    return msg
end


function guomudubao(npc, player)
    lualib:SetPanelSize(npc, 400, 200)
    local msg = "这座神殿自上古就存在，\n"
    msg = msg.."谁也不知道它的来历，\n"
    msg = msg.."只知道每隔一段时间便会开启，\n"
    msg = msg.."里面藏有无尽宝藏。\n\n\n\n"
    msg = msg.."#OFFSET<X:0,Y:4>#<@jump *01*夺宝神殿>\n"
    --msg = msg.."#OFFSET<X:0,Y:4>#<@dubaojl *01*夺宝神殿>\n"
    msg = msg.."#OFFSET<X:0,Y:4>#<@info *01*神殿介绍>\n"
    --msg = msg.."#OFFSET<X:0,Y:4>#<@leave *01*我不敢去>\n"
    msg = msg..""
    return msg
end

function jump(npc, player)
    lualib:SetPanelSize(npc, 400, 200)
    local map = lualib:Player_GetGuidProp(player, lua_role_current_map_id)
    local dgn = lualib:Map_GetCustomVarStr(map, "scheduled_gmfb_dgn_guid")
    if dgn == "" then return "神殿尚未开启！\n " end

    local level = lualib:Player_GetIntProp(player, lua_role_level)
    if level < require_level then return "您的等级过低！\n " end

    if not lualib:Player_IsGoldEnough(player, require_gold, false) then return "您的金币不足"..require_gold.."！\n " end

    if not lualib:Player_SubGold(player, require_gold, false, "扣金币：古墓传送费", "古墓守卫") then
        lualib:SetPanelSize(npc, 400, 200)
        return "扣除金币失败！"
    end

    if lualib:Player_SetDgnTicket(player, dgn) == false then return "您不被许可进入地图！\n \n \n \n \n                                          #OFFSET<X:0,Y:0>##IMAGE<ID:1902700019>##OFFSET<X:0,Y:-2>#" end
    if lualib:Player_EnterDgn(player, "古墓", 0, 0, 0) == false then return "进入地图失败！\n \n \n \n \n                                         #OFFSET<X:0,Y:0>##IMAGE<ID:1902700019>##OFFSET<X:0,Y:-2>#"end
    lualib:SetPanelSize(npc, 400, 200)
    return ""
end

function leave(npc, player)
    return ""
end

function info(npc, player)
    lualib:SetPanelSize(npc, 400, 200)
    local msg = "每天20:00开启，开启时间60分钟。\n"
    msg = msg.."神殿内有无数宝箱，宝箱内藏有各种宝物，\n"
    msg = msg.."其中有一只宝箱藏有一个宝盒，\n"
    msg = msg.."持有宝盒者每几秒获得一定数量元宝，\n"
    msg = msg.."持有宝盒者被击杀，离开地图或下线，宝盒必将掉落，\n"
    msg = msg.."成功保护30分钟后可开启宝盒，宝盒内藏有珍贵宝物，\n"
    msg = msg.."神殿开启60分钟，如55分钟内没人开启宝盒，\n"
    msg = msg.."宝盒将自动开启，宝物将掉落在神殿随机处。\n"
    --msg = msg.."#IMAGE<ID:1902700019>#<@main *01*「返回」>\n"
    return msg
end


---------------商店传送--------------------
function move_shop(npc, player)
    local msg = "我可以将你免费传送到附近的商店\n\n\n"
    msg = msg.."<@MapMoveA#龙城#259#251 *01*「武器店」>　　 "
    msg = msg.."<@MapMoveA#龙城#238#225 *01*「衣服店」>　　 "
    msg = msg.."<@MapMoveA#龙城#226#211 *01*「首饰店」>　　 "
    msg = msg.."<@MapMoveA#龙城#273#276 *01*「杂货店」>　　 \n"
    msg = msg.."<@MapMoveA#龙城#200#277 *01*「药  店」>　　 "
    msg = msg.."<@MapMoveA#龙城#220#228 *01*「书  店」>　　 "
    msg = msg.."<@MapMoveA#龙城#223#297 *01*「仓  库」>　　\n\n\n"
    msg = msg.."　　　　　　　　　　　　　　　　　　　　　　　　　#IMAGE<ID:1902700019>#<@main *01*返 回>\n "
    lualib:SetPanelSize(npc, 400, 200)
    return msg
end

function MapMoveA(npc, player, map_k, x, y)
    if not lualib:Player_MapMoveXY(player, map_k, tonumber(x), tonumber(y), 3) then
        return "跳地图失败.\n\n<@exit_e *01*离开>"
    end

    return ""
end

----------------------险恶传送-----------------



function move_srgm(npc,player)
    lualib:SetPanelSize(npc, 420, 210)
    local msg = [[
	#COLORCOLOR_MAGENTA#地图名称：#COLOREND# 骷髅洞        #COLORCOLOR_MAGENTA#BOSS地图：#COLOREND# 国王陵墓
	#COLORCOLOR_MAGENTA#刷新时间：#COLOREND# 60分钟        #COLORCOLOR_MAGENTA#地图BOSS：#COLOREND# 骷髅精灵
	#COLORCOLOR_MAGENTA#地图产出：#COLOREND#





                                                     #IMAGE<ID:1902700019># <@MapMoveA#废矿入口#57#325 *01*>]]
    local drop = {
        {"精灵之骨","好运卷轴", },--第3行
    }
    local str = "<form default_parent=NpcTalk,Container>"
    local idx = 0
    for k, v in ipairs(drop) do
        local x = 0
        for m, n in ipairs(v) do
            idx = idx + 1
            str = str.. "<itemctrl id=掉落"..idx.." x=".. ((m - 1) * 35 + 7) .." y=".. (k * 35 + 15) .." w=34 h=34 init_item="..n.." count=1/>"
        end
    end
    msg = str.. "<text><![CDATA["..msg.."]]></text></form>"
    return msg
end



function move_fqkq(npc,player)
    if lualib:GetClientType(player) == 2 then
        local msg = [[
#COLORCOLOR_MAGENTA#地图名称：#COLOREND# 猪  洞      #COLORCOLOR_MAGENTA#BOSS地图：#COLOREND# 猪洞四层、五层、七层                   #COLORCOLOR_MAGENTA#刷新时间：#COLOREND# 360分钟     #COLORCOLOR_MAGENTA#地图BOSS：#COLOREND# 虹魔教主、白野猪
有几率掉落：#COLORCOLOR_RED#"炼狱", "幽灵项链", "幽灵手套", "龙之戒指", "魔杖", "生命项链", "思贝儿手镯", "红宝石戒指", "银蛇", "天珠项链", "铂金戒指","三眼手镯","井中月", "无极棍", "裁决之杖", "绿色项链","骑士手镯","力量戒指","骨玉权杖","恶魔铃铛","龙之手镯","紫碧螺","龙纹剑","灵魂项链","心灵手镯", "泰坦戒指", "黑铁头盔",  "皮料", "烈火剑法", "冰咆哮", "召唤神兽", "各职业技能书" #COLOREND#

]]
        return msg
    else
        lualib:SetPanelSize(npc, 490, 260)
        local msg = [[
\n  #COLORCOLOR_MAGENTA#地图名称：#COLOREND# 猪  洞      #COLORCOLOR_MAGENTA#BOSS地图：#COLOREND# 猪洞四层、五层、七层                   #COLORCOLOR_MAGENTA#刷新时间：#COLOREND# 360分钟     #COLORCOLOR_MAGENTA#地图BOSS：#COLOREND# 虹魔教主、白野猪







                                                     ]]
        local drop = {
            {"炼狱", "幽灵项链", "幽灵手套", "龙之戒指", "魔杖", "生命项链", "思贝儿手镯", "红宝石戒指", "银蛇", "天珠项链", "铂金戒指"},--第1行
            {"三眼手镯","井中月", "无极棍", "裁决之杖", "绿色项链", "骑士手镯", "力量戒指", "骨玉权杖", "恶魔铃铛", "龙之手镯", "紫碧螺"},--第2行
            {"龙纹剑", "灵魂项链", "心灵手镯", "泰坦戒指", "黑铁头盔",  "皮料", "烈火剑法", "冰咆哮", "召唤神兽", "各职业技能书", },--第3行
        }
        local str = "<form default_parent=NpcTalk,Container>"
        local idx = 0
        for k, v in ipairs(drop) do
            local x = 0
            for m, n in ipairs(v) do
                idx = idx + 1
                str = str.. "<itemctrl id=掉落"..idx.." x=".. ((m - 1) * 40 + 7) .." y=".. (k * 50 + 15) .." w=34 h=34 init_item="..n.." count=1/>"
            end
        end
        msg = str.. "<text><![CDATA["..msg.."]]></text></form>"
        return msg
    end
end


function move_clmg(npc,player)
    lualib:SetPanelSize(npc, 472, 265)
    local msg = [[
	#COLORCOLOR_MAGENTA#地图名称：#COLOREND# 白日门 #COLORCOLOR_MAGENTA#BOSS地图：#COLOREND# 赤月魔穴、恶魔祭坛
	#COLORCOLOR_MAGENTA#刷新时间：#COLOREND#360分钟 #COLORCOLOR_MAGENTA#地图BOSS：#COLOREND# 赤月恶魔,双头血魔,双头金刚
	#COLORCOLOR_MAGENTA#地图产出：#COLOREND#










                                                             #IMAGE<ID:1902700019># <@move_yes2#白日门#295#327 *01*前往>]]
    local drop = {
        {"炼狱", "幽灵项链", "幽灵手套", "龙之戒指", "魔杖", "生命项链", "思贝儿手镯", "红宝石戒指", "银蛇", "天珠项链", "铂金戒指","无极棍"},--第1行具
        {"裁决之杖", "绿色项链", "骑士手镯", "力量戒指", "骨玉权杖", "恶魔铃铛", "龙之手镯", "紫碧螺", "龙纹剑", "灵魂项链", "心灵手镯","泰坦戒指"},--第2行
        { "圣战头盔", "圣战项链", "圣战手镯", "圣战戒指",  "法神头盔", "法神项链", "法神手镯", "法神戒指","天尊头盔", "天尊项链", "天尊手镯", "天尊戒指", },--第3行
        {"黑铁头盔","井中月","血饮","逍遥扇", "好运卷轴", "烈火剑法","冰咆哮","召唤神兽",   },--第4行
    }
    local str = "<form default_parent=NpcTalk,Container>"
    local idx = 0
    for k, v in ipairs(drop) do
        local x = 0
        for m, n in ipairs(v) do
            idx = idx + 1
            str = str.. "<itemctrl id=掉落"..idx.." x=".. ((m - 1) * 35 + 7) .." y=".. (k * 35 + 15) .." w=34 h=34 init_item="..n.." count=1/>"
        end
    end
    msg = str.. "<text><![CDATA["..msg.."]]></text></form>"
    return msg
end

function move_fmkq(npc,player)
    lualib:SetPanelSize(npc, 472, 230)
    local msg = [[
	#COLORCOLOR_MAGENTA#地图名称：#COLOREND# 封  魔        #COLORCOLOR_MAGENTA#BOSS地图：#COLOREND# 封魔殿、死亡神殿
	#COLORCOLOR_MAGENTA#刷新时间：#COLOREND#180、360分钟   #COLORCOLOR_MAGENTA#地图BOSS：#COLOREND# 虹魔教主、暗之虹魔教主
	#COLORCOLOR_MAGENTA#地图产出：#COLOREND#               #COLORCOLOR_MAGENTA#前往地图：#COLOREND# 免费








                                                             #IMAGE<ID:1902700019># <@MapMoveA#封魔矿区#58#322 *01*前往>]]
    local drop = {
        {"炼狱", "幽灵项链", "幽灵手套", "龙之戒指", "魔杖", "生命项链", "思贝儿手镯", "红宝石戒指", "银蛇", "天珠项链", "铂金戒指","无极棍"},--第1行具
        {"裁决之杖", "绿色项链", "骑士手镯", "力量戒指", "骨玉权杖", "恶魔铃铛", "龙之手镯", "紫碧螺", "龙纹剑", "灵魂项链", "心灵手镯","泰坦戒指"},--第2行
        {"龙牙","井中月","黑铁头盔","好运卷轴","鸿运卷轴", "封魔残卷", "封印鉴定符", "野猪皮","烈火剑法","冰咆哮", "召唤神兽", "战士技能书", },--第3行
        { "霓裳羽衣","法师技能书", "道士技能书"},--第3行
    }
    local str = "<form default_parent=NpcTalk,Container>"
    local idx = 0
    for k, v in ipairs(drop) do
        local x = 0
        for m, n in ipairs(v) do
            idx = idx + 1
            str = str.. "<itemctrl id=掉落"..idx.." x=".. ((m - 1) * 35 + 7) .." y=".. (k * 35 + 15) .." w=34 h=34 init_item="..n.." count=1/>"
        end
    end
    msg = str.. "<text><![CDATA["..msg.."]]></text></form>"
    return msg
end

function move_wmsm(npc,player)
    lualib:SetPanelSize(npc, 437, 220)
    local msg = [[
	#COLORCOLOR_MAGENTA#地图名称：#COLOREND# 沃玛祠庙     #COLORCOLOR_MAGENTA#BOSS地图：#COLOREND# 沃玛教主大厅
	#COLORCOLOR_MAGENTA#刷新时间：#COLOREND#180分钟       #COLORCOLOR_MAGENTA#地图BOSS：#COLOREND# 沃玛教主
	#COLORCOLOR_MAGENTA#地图产出：#COLOREND#







                                                        #IMAGE<ID:1902700019># <@MapMoveA#沃玛祠庙1#115#122 *01*>]]
    local drop = {
        {"炼狱", "幽灵项链", "幽灵手套", "龙之戒指", "魔杖", "生命项链", "思贝儿手镯", "红宝石戒指", "银蛇", "天珠项链", "铂金戒指",},--第1行具

        {"沃玛号角","三眼手镯","好运卷轴", "战士技能书","法师技能书", "道士技能书" },--第3行
    }
    local str = "<form default_parent=NpcTalk,Container>"
    local idx = 0
    for k, v in ipairs(drop) do
        local x = 0
        for m, n in ipairs(v) do
            idx = idx + 1
            str = str.. "<itemctrl id=掉落"..idx.." x=".. ((m - 1) * 35 + 7) .." y=".. (k * 35 + 15) .." w=34 h=34 init_item="..n.." count=1/>"
        end
    end
    msg = str.. "<text><![CDATA["..msg.."]]></text></form>"
    return msg
end


function move_wgd(npc,player)
    lualib:SetPanelSize(npc, 437, 220)
    local msg = [[
	#COLORCOLOR_MAGENTA#地图名称：#COLOREND#  蜈蚣洞        #COLORCOLOR_MAGENTA#BOSS地图：#COLOREND# 死亡棺材
	#COLORCOLOR_MAGENTA#刷新时间：#COLOREND#  120分钟       #COLORCOLOR_MAGENTA#地图BOSS：#COLOREND# 触龙神
	#COLORCOLOR_MAGENTA#地图产出：#COLOREND#







                                                        #IMAGE<ID:1902700019># <@MapMoveA#地牢1层东#335#402 *01*>]]
    local drop = {
        {"炼狱", "幽灵项链", "幽灵手套", "龙之戒指", "魔杖", "生命项链", "思贝儿手镯", "红宝石戒指", "银蛇", "天珠项链", "铂金戒指",},--第1行具
        {"无极棍","井中月","裁决之杖","骨玉权杖","龙纹剑", "三眼手镯","好运卷轴", "战士技能书","法师技能书", "道士技能书" },--第3行"封魔残卷"
    }
    local str = "<form default_parent=NpcTalk,Container>"
    local idx = 0
    for k, v in ipairs(drop) do
        local x = 0
        for m, n in ipairs(v) do
            idx = idx + 1
            str = str.. "<itemctrl id=掉落"..idx.." x=".. ((m - 1) * 35 + 7) .." y=".. (k * 35 + 15) .." w=34 h=34 init_item="..n.." count=1/>"
        end
    end
    msg = str.. "<text><![CDATA["..msg.."]]></text></form>"
    return msg
end


function move_smrk(npc,player)
    lualib:SetPanelSize(npc, 437, 220)
    local msg = [[
	#COLORCOLOR_MAGENTA#地图名称：#COLOREND#石  墓            #COLORCOLOR_MAGENTA#BOSS地图：#COLOREND# 石墓七层
	#COLORCOLOR_MAGENTA#刷新时间：#COLOREND#120分钟           #COLORCOLOR_MAGENTA#地图BOSS：#COLOREND# 石墓尸王
	#COLORCOLOR_MAGENTA#地图产出：#COLOREND#







                                                        #IMAGE<ID:1902700019># <@MapMoveA#石窟入口#76#63 *01*>]]
    local drop = {
        {"炼狱", "幽灵项链", "幽灵手套", "龙之戒指", "魔杖", "生命项链", "思贝儿手镯", "红宝石戒指", "银蛇", "天珠项链", "铂金戒指",},--第1行具
        {"无极棍","井中月","裁决之杖","骨玉权杖","龙纹剑", "三眼手镯","好运卷轴", "野猪皮",},--第3行
        {"烈火剑法","冰咆哮", "召唤神兽", "战士技能书","法师技能书", "道士技能书", },--第3行
    }
    local str = "<form default_parent=NpcTalk,Container>"
    local idx = 0
    for k, v in ipairs(drop) do
        local x = 0
        for m, n in ipairs(v) do
            idx = idx + 1
            str = str.. "<itemctrl id=掉落"..idx.." x=".. ((m - 1) * 35 + 7) .." y=".. (k * 35 + 15) .." w=34 h=34 init_item="..n.." count=1/>"
        end
    end
    msg = str.. "<text><![CDATA["..msg.."]]></text></form>"
    return msg
end


function move_sm(npc,player)
    lualib:SetPanelSize(npc, 472, 220)
    local msg = [[
	#COLORCOLOR_MAGENTA#地图名称：#COLOREND# 祖犸寺庙     #COLORCOLOR_MAGENTA#BOSS地图：#COLOREND# 祖犸教主之家
	#COLORCOLOR_MAGENTA#刷新时间：#COLOREND#180分钟       #COLORCOLOR_MAGENTA#地图BOSS：#COLOREND# 祖犸教主
	#COLORCOLOR_MAGENTA#地图产出：#COLOREND#







                                                              #IMAGE<ID:1902700019># <@move_yes#祖犸寺庙入口#13#32 *01*>]]
    local drop = {
        {"炼狱", "幽灵项链", "幽灵手套", "龙之戒指", "魔杖", "生命项链", "思贝儿手镯", "红宝石戒指", "银蛇", "天珠项链", "铂金戒指","无极棍"},--第1行具
        {"裁决之杖", "绿色项链", "骑士手镯", "力量戒指", "骨玉权杖", "恶魔铃铛", "龙之手镯", "紫碧螺", "龙纹剑", "灵魂项链", "心灵手镯","泰坦戒指"},--第2行
        {"怒斩","井中月","黑铁头盔","好运卷轴","鸿运卷轴",  "召唤神兽", "烈火剑法", "冰咆哮", },--第3行
    }
    local str = "<form default_parent=NpcTalk,Container>"
    local idx = 0
    for k, v in ipairs(drop) do
        local x = 0
        for m, n in ipairs(v) do
            idx = idx + 1
            str = str.. "<itemctrl id=掉落"..idx.." x=".. ((m - 1) * 35 + 7) .." y=".. (k * 35 + 15) .." w=34 h=34 init_item="..n.." count=1/>"
        end
    end
    msg = str.. "<text><![CDATA["..msg.."]]></text></form>"
    return msg
end

function hdcc(npc,player)
    lualib:SetPanelSize(npc, 472, 260)
    local msg = [[
	#COLORCOLOR_MAGENTA#地图名称：#COLOREND# 海底沉船     #COLORCOLOR_MAGENTA#BOSS地图：#COLOREND# 船仓、秘境
	#COLORCOLOR_MAGENTA#刷新时间：#COLOREND# 60、360分钟  #COLORCOLOR_MAGENTA#地图BOSS：#COLOREND# 侍从、海妖、歌妖、海魔
	#COLORCOLOR_MAGENTA#地图产出：#COLOREND#              #COLORCOLOR_MAGENTA#前往地图：#COLOREND#










                                                             #IMAGE<ID:1902700019># <@hdcc_sm *01*前往>]]
    local drop = {
        {"光芒项链", "光芒护腕", "光芒道戒", "光芒腰带", "光芒道靴", "真魂项链", "真魂手镯", "真魂戒指", "真魂腰带", "真魂道靴", "天龙盔", "玄天"},--第1行具
        {"烈焰项链", "烈焰护腕", "烈焰魔戒", "烈焰腰带", "烈焰魔靴", "圣魔项链", "圣魔手镯", "圣魔戒指", "圣魔腰带", "圣魔法靴", "魔龙盔", "镇天"},--第2行
        {"雷霆项链", "雷霆护腕", "雷霆战戒", "雷霆腰带", "雷霆战靴", "战神项链", "战神手镯", "战神戒指", "战神腰带", "战神圣靴", "圣龙盔", "开天"},--第3行
        {"凰天魔衣", "凤天魔甲", "好运卷轴", "封印鉴定符","书页",  },--第4行
    }
    local str = "<form default_parent=NpcTalk,Container>"
    local idx = 0
    for k, v in ipairs(drop) do
        local x = 0
        for m, n in ipairs(v) do
            idx = idx + 1
            str = str.. "<itemctrl id=掉落"..idx.." x=".. ((m - 1) * 35 + 7) .." y=".. (k * 35 + 15) .." w=34 h=34 init_item="..n.." count=1/>"
        end
    end
    msg = str.. "<text><![CDATA["..msg.."]]></text></form>"
    return msg
end

function hdcc_sm(npc, player)
    lualib:SetPanelSize(npc, 400, 200)
    local msg = "需通过北边海上的船夫处（407：105）前往！\n"
    --msg = msg.."本地图1－4层开区7天后开放，最后一层合区后开放！"
    return msg
end


function fmzd(npc,player)
    lualib:SetPanelSize(npc, 472, 330)
    local msg = [[
	#COLORCOLOR_MAGENTA#地图名称：#COLOREND# 伏魔之地     #COLORCOLOR_MAGENTA#BOSS地图：#COLOREND# 伏魔之地
	#COLORCOLOR_MAGENTA#刷新时间：#COLOREND# ？分钟       #COLORCOLOR_MAGENTA#地图BOSS：#COLOREND# 各大地图BOSS
	#COLORCOLOR_MAGENTA#地图产出：#COLOREND#              #COLORCOLOR_MAGENTA#前往地图：#COLOREND#














                                                             #IMAGE<ID:1902700019># <@fmzd_sm *01*前往>]]
    local drop = {
        {"炼狱", "幽灵项链", "幽灵手套", "龙之戒指", "魔杖", "生命项链", "思贝儿手镯", "红宝石戒指", "银蛇", "天珠项链", "铂金戒指","无极棍"},--第1行具
        {"裁决之杖", "绿色项链", "骑士手镯", "力量戒指", "骨玉权杖", "恶魔铃铛", "龙之手镯", "紫碧螺", "龙纹剑", "灵魂项链", "心灵手镯","泰坦戒指"},--第2行
        {"怒斩", "圣战头盔", "圣战项链", "圣战手镯", "圣战戒指", "龙牙", "法神头盔", "法神项链", "法神手镯", "法神戒指", "黑铁头盔","井中月"},--第3行
        {"逍遥扇", "天尊头盔", "天尊项链", "天尊手镯", "天尊戒指","屠龙", "嗜魂法杖","光芒道袍(男)", "光芒道袍(女)", "烈焰魔衣(男)", "烈焰魔衣(女)", "雷霆战甲(男)", },--第4行
        {"雷霆战甲(女)", "光芒项链", "光芒护腕", "光芒道戒", "光芒腰带", "光芒道靴", "烈焰项链", "烈焰护腕", "烈焰魔戒", "烈焰腰带", "烈焰魔靴","雷霆项链",  },--第5行
        {"雷霆护腕", "雷霆战戒", "雷霆腰带", "雷霆战靴","血饮","野猪皮", "好运卷轴", "封印鉴定符", "烈火剑法","冰咆哮","召唤神兽", "书页"},--第5行
    }
    local str = "<form default_parent=NpcTalk,Container>"
    local idx = 0
    for k, v in ipairs(drop) do
        local x = 0
        for m, n in ipairs(v) do
            idx = idx + 1
            str = str.. "<itemctrl id=掉落"..idx.." x=".. ((m - 1) * 35 + 7) .." y=".. (k * 35 + 15) .." w=34 h=34 init_item="..n.." count=1/>"
        end
    end
    msg = str.. "<text><![CDATA["..msg.."]]></text></form>"
    return msg
end

function fmzd_sm(npc, player)
    lualib:SetPanelSize(npc, 400, 200)
    local msg = "需使用1点声望在济世善人处换取伏魔卷轴，\n"
    msg = msg.."并双击此卷轴进入（有失败几率）。\n"
    --msg = msg.."本地图开区10天后开放。"
    return msg
end

function move_huanj(npc,player)
    lualib:SetPanelSize(npc, 472, 300)
    local msg = [[
	#COLORCOLOR_MAGENTA#地图名称：#COLOREND# 幻  境           #COLORCOLOR_MAGENTA#前往地图：#COLOREND#需 1 声望
	#COLORCOLOR_MAGENTA#地图BOSS：#COLOREND# 重装使者,虹魔教主,双头金刚,双头血魔,赤月恶魔,恶魔之主
	#COLORCOLOR_MAGENTA#地图产出：#COLOREND#












                                                               #IMAGE<ID:1902700019>#<@move_yes4#幻境1层#75#76 *01*前往>]]
    local drop = {
        {"炼狱", "幽灵项链", "幽灵手套", "龙之戒指", "魔杖", "生命项链", "思贝儿手镯", "红宝石戒指", "银蛇", "天珠项链", "铂金戒指","无极棍"},--第1行具
        {"裁决之杖", "绿色项链", "骑士手镯", "力量戒指", "骨玉权杖", "恶魔铃铛", "龙之手镯", "紫碧螺", "龙纹剑", "灵魂项链", "心灵手镯","泰坦戒指"},--第2行
        {"怒斩", "圣战头盔", "圣战项链", "圣战手镯", "圣战戒指", "龙牙", "法神头盔", "法神项链", "法神手镯", "法神戒指", "黑铁头盔","井中月"},--第3行
        {"逍遥扇", "血饮", "天尊头盔", "天尊项链", "天尊手镯", "天尊戒指","天尊道袍","天师长袍", "法神披风", "霓裳羽衣","天魔神甲","圣战宝甲",  },--第4行
        {"光芒项链", "光芒护腕", "光芒道戒", "光芒腰带", "光芒道靴", "烈焰项链", "烈焰护腕", "烈焰魔戒", "烈焰腰带", "烈焰魔靴","雷霆项链","雷霆护腕",  },--第4行
        { "雷霆战戒", "雷霆腰带", "雷霆战靴", "屠龙", "嗜魂法杖","野猪皮", "好运卷轴", "封印鉴定符","封魔残卷", "书页"},--第5行
    }
    local str = "<form default_parent=NpcTalk,Container>"
    local idx = 0
    for k, v in ipairs(drop) do
        local x = 0
        for m, n in ipairs(v) do
            idx = idx + 1
            str = str.. "<itemctrl id=掉落"..idx.." x=".. ((m - 1) * 35 + 7) .." y=".. (k * 35 + 15) .." w=34 h=34 init_item="..n.." count=1/>"
        end
    end
    msg = str.. "<text><![CDATA["..msg.."]]></text></form>"
    return msg
end

function move_yes(npc, player, map_k, x, y)
    lualib:SetPanelSize(npc, 400, 200)
    if lualib:Player_SubGold(player, 10000, false, "sdfsd", "sdfsd") then
        lualib:Player_MapMoveXY(player, map_k, tonumber(x), tonumber(y), 5)
    else
        return "你的金币不足10000\n"
    end
    return ""
end

function move_yes2(npc, player, map_k, x, y)
    lualib:SetPanelSize(npc, 400, 200)
    if lualib:Player_SubGold(player, 20000, false, "sdfsd", "sdfsd") then
        lualib:Player_MapMoveXY(player, map_k, tonumber(x), tonumber(y), 5)
    else
        return "你的金币不足20000\n"
    end
    return ""
end

function move_yes3(npc, player, map_k, x, y)
    lualib:SetPanelSize(npc, 400, 200)
    if lualib:Player_SubGold(player, 30000, false, "sdfsd", "sdfsd") then
        lualib:Player_MapMoveXY(player, map_k, tonumber(x), tonumber(y), 5)
    else
        return "你的金币不足30000\n"
    end
    return ""
end

function move_yes4(npc, player, map_k, x, y)
    lualib:SetPanelSize(npc, 400, 200)
    local index = lualib:GetDBNum("mapopenlv")
    if index < 2 then
        return "抱歉，史诗篇章（二）尚未开启。"
    end
    if lualib:Prestige(player) >= 1 then
        lualib:SetPrestige(player, lualib:Prestige(player) - 1)
        lualib:Player_MapMoveXY(player, map_k, tonumber(x), tonumber(y), 5)
    else
        return "你的声望不足1点\n"
    end
    return ""
end
--------------------------------组队副本----------------------------------------------------

function main_zhudui(npc, player)
    local msg = [[
年轻人，你好！欢迎来到组队副本，我可以给你带来丰厚的报酬！
进入此副本需要消耗“组队卷轴”一枚，由队长带队进入。地图一共可分为三层，越到后面怪物爆率越高。

#IMAGE1902700018#<@Team *01*组队挑战组队副本>\n\n\n\n
　　　　　　　　　  　　　　　　　　　　　　　#IMAGE<ID:1902700019>#<@main *01* 返 回>
]]
    lualib:SetPanelSize(npc, 400, 200)
    return msg
end

function Team(npc, player)
    lualib:SetPanelSize(npc, 400, 200)
    local name = lualib:Name(player)
    if not lualib:Player_IsTeamLeader(player) then
        return "你不是队长,只有队长才有资格带领队员进入副本\n\n\n\n\n\n\n　　　　　　　　　　　　　　　　　　　　　　　　　#IMAGE<ID:1902700019>#<@main *01*返 回>"
    end
    local players = lualib:Player_GetTeamList(player)
    local req, member = CheckDgnNum(players, npc)
    if req == false then
        return "抱歉,队友["..member.."]距离太远，无法进入地图失败。\n\n\n\n\n\n\n　　　　　　　　　　　　　　　　　　　　　　　　　#IMAGE<ID:1902700019>#<@main *01*返 回>"
    end
    if not lualib:DelItem(player, itemKey, 1, 2, "组队副本传送", npc) then
        return "您的背包里一个"..itemKey.."都没有。\n\n\n\n\n\n\n　　　　　　　　　　　　　　　　　　　　　　　　　#IMAGE<ID:1902700019>#<@main *01*返 回>"
    end
    local map = lualib:Map_CreateDgn(mapkey, true, ztimesz)
    for i = 1, #players do
        lualib:Player_SetDgnTicket(players[i], map)
        lualib:Player_EnterDgn(players[i], mapkey, 52, 87, 5)
        lualib:DelayCall(players[i], _ztimesz * 1000, "callback", "")
    end
    lualib:SysMsg_SendBroadcastMsg(name.."带领自己的团队闯入了"..mapkey..",大家为他们祈祷吧!", lualib:Name(npc))
    return ""
end

function callback(player)
    local map = lualib:MapGuid(player)
    local name = lualib:KeyName(map)
    if name ~= "墓穴组队一" and name ~= "墓穴组队二" and name ~= "墓穴组队三" then

    else
        lualib:Player_MapMoveXY(player, "龙城", 252, 272, 3)
    end
end

function CheckDgnNum(players, npc)
    for i = 1, #players do
        if lualib:Distance(players[i], npc) > 8 then
            return false, lualib:Name(players[i])
        end
    end
    return true
end
-------------------------------------65465465-----------------------------------------------

function rongsi_info(npc, player)
    local msg = [[你有神秘绒丝在身上吗？有的话，那我可以帮你编织!
魔龙套装升级是必须拥有雷霆绒丝、烈焰绒丝、光芒绒丝
缺少这些神秘属性的绒丝！可无法成功升级哦！
如果你给我100W金币的话！我很愿意帮你编织！
我确认身上有神秘绒丝，<@bianzhi *01*请帮我编织>
]]
    return msg
end

function bianzhi(npc, player)

    if not lualib:Player_IsGoldEnough(player, 1000000, false) then
        return "你没有神秘绒丝或者100W编织费用！\n<@main *01*返回>"
    end

    if not lualib:DelItem(player, "神秘绒丝", 1, 2, "", "") then
        return "你没有神秘绒丝或者100W编织费用！\n<@main *01*返回>"
    else
        if not lualib:Player_SubGold(player, 1000000, false, "编制绒丝", "") then
            returnreturn "你没有神秘绒丝或者100W编织费用！\n<@main *01*返回>"
        end
    end

    local rand = math.random(1, 3)
    local item_t = {"雷霆绒丝", "烈焰绒丝", "光芒绒丝"}

    if not lualib:AddItem(player, item_t[rand], 1, false, "", "") then
        return "游戏内没有此道具！"
    end
    local name = lualib:Name(player)

    local s = name.."花费100W请天工神剪为自己编织了"..item_t[rand]
    lualib:SysMsg_SendBroadcastMsg(s, "")
    return ""
end



--「我有卷轴，我要组队除魔」
function team_cm(npc, player)
    local msg = ""
    msg = msg.."不同的卷轴通向不同的地牢，你们也将会遇到不同的恶魔。\n 首先你会进入一间试练室，试练室最多能够停留9秒钟\n"
    msg = msg.."在试练室中，只需点击试练员即可进入下一层\n 对了有个小秘密告诉你\n"
    msg = msg.."在地牢最底层所有出没的恶魔身上藏有稀世珍宝，\n "
    msg = msg.."现在让我们看看你有什么卷轴吧，我在你们去那里挑战群魔。\n \n"
    msg = msg.."#IMAGE1902700018# <@move_cm#矿洞 *01*去矿洞组队除魔>　　　　　　"
    msg = msg.."#IMAGE1902700018# <@move_cm#神殿 *01*去神殿组队除魔>\n"
    msg = msg.."#IMAGE1902700018# <@move_cm#邪窟 *01*去邪窟组队除魔>　　　　　　"
    msg = msg.."#IMAGE1902700018# <@move_cm#地穴 *01*去地穴组队除魔>\n"
    msg = msg.."#IMAGE1902700018# <@move_cm#石墓 *01*去石墓组队除魔>　　　　　　"

    msg = msg.."　　　　　　　　　　　　　　<@main *01*「返 回」>"
    return msg
end

function move_cm(npc, player, str)
    if lualib:Player_GetTeamGuid(player) == "" then
        local msg = "「条件不够」:除魔需要组队前往！你好象还未组队！\n"
        msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
        return msg
    end

    if lualib:Player_IsTeamLeader(player) == false then
        local msg = "「条件不够」:除魔需要队长带领！你不是队长！\n"
        msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
        return msg
    end

    local map_tbl =
    {
        ["矿洞"] = {"矿洞组队卷轴", 40, "矿洞试炼屋1" },
        ["神殿"] = {"神殿组队卷轴", 40, "神殿试炼屋1" },
        ["邪窟"] = {"邪窟组队卷轴", 40, "邪窟试炼屋1" },
        ["地穴"] = {"地穴组队卷轴", 40, "地穴试炼屋1" },
        ["石墓"] = {"石墓组队卷轴", 40, "石墓试炼屋1" },

    }
    local map_k = map_tbl[str][3]
    local map = lualib:Map_GetMapGuid(map_k)
    local player_n = lualib:Map_GetPlayerCount(map, true)
    if player_n >= 1 then
        local msg = "该地图已有玩家存在，请等待！\n"
        msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
        return msg
    end

    local item_s = map_tbl[str][1]
    if lualib:ItemCount(player, item_s) < 1 then
        local msg = "「条件不够」:除魔需要"..item_s.."一张！\n"
        msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
        return msg
    end


    local level_s = map_tbl[str][2]

    if lualib:Level(player) < level_s then
        local msg = "「条件不够」:除魔需要人物"..level_s.."级以上！\n"
        msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
        return msg
    end

    local TeamList = lualib:Player_GetTeamList(player)
    for i = 1, #TeamList do
        if lualib:Level(TeamList[i]) < level_s then
            local person_n = lualib:Name(TeamList[i])
            local msg = "「条件不够」:除魔需要人物"..level_s.."级以上！队员「"..person_n.."」等级不足！\n"
            msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
            return msg
        end

        local distance = lualib:Distance(TeamList[i], npc)
        if distance > 15 then
            local msg = "「条件不够」:队员「"..person_n.."」不在身边！\n"
            msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
            return msg
        end
    end

    if lualib:TakeItem(player, item_s, 1, "", "") == true then
        lualib:Player_MapMove(player, map_k)
        for i = 1, #TeamList do
            lualib:Player_MapMove(TeamList[i], map_k)
        end
        lualib:Map_BatchGenMonster(map, "试炼守护者", 1, false)

    else
        local msg = "删除物品「"..item_s.."」出错！\n"
        msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
        return msg
    end
    return ""
end



--「我要解除封印」
function jc_fengy(npc, player)
    local msg = ""
    msg = msg.."那么让我看看你要解封什么吧！只要你有足够的封印首饰\n"
    msg = msg.."解封需要'伏魔令'快快去寻找镇魔护卫吧！！\n"
    msg = msg.."什么,你竟然不知道'镇魔护卫'在哪里?\n"
    msg = msg.."护卫就在除魔组队任务地图最深层！找到他通过重重试炼！\n"
    msg = msg.."就可以获得'伏魔令'！快携带受到封印的装备去找'镇魔护卫'吧!\n"
    msg = msg.."对了,我还要告诉你一个秘密!除魔的路上!\n"
    msg = msg.."会遇到玛砝大陆的五大教主阻拦你!勇士!好运!\n\n"

    msg = msg.."　　　　　　　　　　　　　　<@main *01*「返 回」>"
    return msg
end



--「解救天工神剪」
function jj_tiangsj(npc, player)
    local msg = ""
    msg = msg.."只要你拥有矿洞组队卷轴、神殿组队卷轴、邪窟组队卷轴、\n"
    msg = msg.."地穴组队卷轴、石墓组队卷轴这五种卷轴中的任意一件，我\n"
    msg = msg.."就可以送你前往地下迷宫，那里也有一个地下城守卫\n"
    msg = msg.."他可以送你去宫殿长廊，前去解救天工神剪\n\n"
    msg = msg.."#IMAGE1902700018# <@move_jj_1 *01*组队前往地下迷宫>　　　　　　"
    msg = msg.."#IMAGE1902700018# <@move_jj_2 *01*单独前往地下迷宫>\n"

    msg = msg.."　　　　　　　　　　　　　　<@main *01*「返 回」>"
    return msg
end


function move_jj_1(npc, player)
    if lualib:Player_GetTeamGuid(player) == "" then
        local msg = "「条件不够」:你好象还未组队！\n"
        msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
        return msg
    end

    if lualib:Player_IsTeamLeader(player) == false then
        local msg = "「条件不够」:你不是队长！\n"
        msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
        return msg
    end

    local level_s = 40
    if lualib:Level(player) < level_s then
        local msg = "「条件不够」:解救天工神剪需要"..level_s.."级！"
        msg = msg.."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
        return msg
    end

    if  lualib:ItemCount(player, "矿洞组队卷轴") < 1 and
            lualib:ItemCount(player, "神殿组队卷轴") < 1 and
            lualib:ItemCount(player, "邪窟组队卷轴") < 1 and
            lualib:ItemCount(player, "地穴组队卷轴") < 1 and
            lualib:ItemCount(player, "石墓组队卷轴") < 1 then
        local msg = "「条件不够」:解救天工神剪需要五种卷轴中的任意一件！"
        msg = msg.."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
        return msg
    end

    local TeamList = lualib:Player_GetTeamList(player)
    for i = 1, #TeamList do
        if lualib:Level(TeamList[i]) < level_s then
            local person_n = lualib:Name(TeamList[i])
            local msg = "「条件不够」:除魔需要人物"..level_s.."级以上！队员「"..person_n.."」等级不足！\n"
            msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
            return msg
        end
        local distance = lualib:Distance(TeamList[i], npc)
        if distance > 15 then
            local msg = "「条件不够」:队员「"..person_n.."」不在身边！\n"
            msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
            return msg
        end
    end

    local item_tbl = {"矿洞组队卷轴", "神殿组队卷轴", "邪窟组队卷轴", "地穴组队卷轴", "石墓组队卷轴"}
    for i = 1, #item_tbl do
        if lualib:ItemCount(player, item_tbl[i]) >= 1 then
            if TakeItem(player, item_tbl[i], 1, "", "") == true then
                local map_k = "地下宫殿迷宫"
                lualib:Player_MapMove(player, map_k)
                for i = 1, #TeamList do
                    lualib:Player_MapMove(TeamList[i], map_k)
                end
                return ""
            else
                local msg = "删除物品「"..item_tbl[i].."」出错！\n"
                msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
                return msg
            end
        end
    end

    return ""
end

function move_jj_2(npc, player)
    if lualib:Level(player) < 40 then
        local msg = "「条件不够」:解救天工神剪需要等级40级！"
        msg = msg.."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
        return msg
    end

    if  lualib:ItemCount(player, "矿洞组队卷轴") < 1 and
            lualib:ItemCount(player, "神殿组队卷轴") < 1 and
            lualib:ItemCount(player, "邪窟组队卷轴") < 1 and
            lualib:ItemCount(player, "地穴组队卷轴") < 1 and
            lualib:ItemCount(player, "石墓组队卷轴") < 1 then
        local msg = "「条件不够」:解救天工神剪需要五种卷轴中的任意一件！"
        msg = msg.."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
        return msg
    end

    local item_tbl = {"矿洞组队卷轴", "神殿组队卷轴", "邪窟组队卷轴", "地穴组队卷轴", "石墓组队卷轴"}
    for i = 1, #item_tbl do
        if lualib:ItemCount(player, item_tbl[i]) >= 1 then
            if TakeItem(player, item_tbl[i], 1, "", "") == true then
                local map_k = "地下宫殿迷宫"
                lualib:Player_MapMove(player, map_k)
                return ""
            else
                local msg = "删除物品「"..item_tbl[i].."」出错！\n"
                msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
                return msg
            end
        end
    end

    return ""
end

------------------------------------烟花之地------------------------------------------------------

function fire_tm(npc, player)
    lualib:SetPanelSize(npc, 410, 200)
    local StartServerTime = lualib:GetConstVar("StartServerTime")
    local StartServerTime_int = lualib:Str2Time(StartServerTime)
    local map_open_time = 0

    local times = lualib:GetAllTime()
    local map_open_time = StartServerTime_int + 3600 * 24 * 0
    if times < map_open_time then
        local open_time_str = lualib:Time2Str("%Y-%m-%d %H:%M", map_open_time)
        return "烟花之地将在"..open_time_str.."后开放！"
    end



    local msg = ""
    msg = msg.."屠魔战场的入口就在我的身后、只是通常都不开启\n"
    msg = msg.."焰火是有灵气的东西，我懂得如何发挥它的灵气并用它打开入口\n"
    msg = msg.."给我三个相同的焰火，我就能帮您打开一次屠魔战场的入口\n"
    msg = msg.."不同种类的焰火能让你去到不同的屠魔战场，因为屠魔战场不止一个\n"
    msg = msg.."但凡人在那逗留过久会渐染魔性，故每次进入您只有30分钟时间\n"
    msg = msg.."等您30分钟自动返回盟重后，再安心清算获得的大量宝物和经验吧。\n"
    msg = msg.."您带来了哪种焰火呢\n\n"
    --msg = msg.."#IMAGE1902700018# <@fire_ex#一心 *01*一心一意>　　　　"
    msg = msg.."#IMAGE1902700018# <@fire_ex#心心 *01*心心相印>　　　　"
    msg = msg.."#IMAGE1902700018# <@fire_ex#飞火 *01*飞火流星>\n"
    --msg = msg.."#IMAGE1902700018# <@fire_ex#浪漫 *01*浪漫星雨>　　　　"
    --msg = msg.."#IMAGE1902700018# <@fire_ex#绮梦 *01*绮梦幻想>\n"


    msg = msg.."　　　　　　　　　  　　　　　　　　　　  　　　#IMAGE<ID:1902700019>#<@main *01*返 回>"
    return msg
end

function fire_ex(npc, player, str)
    local map_tbl =
    {
        ["一心"] = {"屠魔战场-一心", "一心一意", 3},
        ["心心"] = {"屠魔战场-心心", "心心相印", 3},
        ["飞火"] = {"屠魔战场-飞火", "飞火流星", 3},
        ["浪漫"] = {"屠魔战场-浪漫", "浪漫星雨", 3},
        ["绮梦"] = {"屠魔战场-绮梦", "绮梦幻想", 3},
    }
    local map_k = map_tbl[str][1]
    local item_k = map_tbl[str][2]
    local item_n = map_tbl[str][3]

    if lualib:ItemCount(player, item_k) < item_n then
        local msg = "你都没有"..item_n.."个"..item_k.."！不能进入！\n"
        msg = msg .."\n\n\n\n\n                   　　　　　　　　　　　　　　#IMAGE<ID:1902700019>#<@main *01*返 回>"
        lualib:SetPanelSize(npc, 400, 200)
        return msg
    end

    lualib:DelItem(player, item_k, item_n, 2, "屠魔", "")
    lualib:Player_MapMove(player, map_k)
    lualib:SysMsg_SendBroadcastMsg(lualib:Name(player).."进入了"..map_k.."，★★★此地图双倍经验，全屏怪物，升级最佳地图★★★","[系统公告]")  --提示消息
    return ""
end


--「神秘组队卷轴的消息」
function team_msg(npc, player)
    local msg = ""
    msg = msg.."组队卷轴可在玛砝各地图BOSS以及焰火地图获得。\n"
    msg = msg.."如果你实在找不到的话\n"
    msg = msg.."我也可以帮你打造组队卷轴哦\n"
    msg = msg.."不过这个手艺失传已久,我也有些生疏了呢!\n"
    msg = msg.."所以你需要提供8张书页，让我看看能不能在这些书页上找到回忆\n"
    msg = msg.."如果你确定需要我帮你做组队卷轴的话,那快给我8张书页吧。\n\n"
    msg = msg.."#IMAGE1902700018# <@team_huanj#矿洞 *01*矿洞组队卷轴>　　　　　　"
    msg = msg.."#IMAGE1902700018# <@team_huanj#神殿 *01*神殿组队卷轴>\n"
    msg = msg.."#IMAGE1902700018# <@team_huanj#邪窟 *01*邪窟组队卷轴>　　　　　　"
    msg = msg.."#IMAGE1902700018# <@team_huanj#地穴 *01*地穴组队卷轴>\n"
    msg = msg.."#IMAGE1902700018# <@team_huanj#石墓 *01*石墓组队卷轴>　　　　　　"


    msg = msg.."　　　　　　　　　　　　　　<@main *01*「返 回」>"
    return msg
end

function team_huanj(npc, player, str)
    if lualib:ItemCount(player, "书页") < 8 then
        local msg = "对不起，你没有8张书页！\n"
        msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
        return msg
    end

    local hj_tbl =
    {
        ["矿洞"] = "矿洞组队卷轴",
        ["神殿"] = "神殿组队卷轴",
        ["邪窟"] = "邪窟组队卷轴",
        ["地穴"] = "地穴组队卷轴",
        ["石墓"] = "石墓组队卷轴",
    }
    local goal_ik = hj_tbl[str]

    if lualib:DelItem(player, "书页", 8, 2, "兑换", "") then
        lualib:AddItem(player, goal_ik, 1, false, "兑换", "")
    end

    local msg = "恭喜！成功兑换一张"..goal_ik.."。\n"
    msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
    return msg
end


--「洞察魔兽信息」
function apperceive(npc, player)
    lualib:SetPanelSize(npc, 400, 200)
    local msg = ""
    msg = msg.."相传在天藏大陆的某些角落，有一批恶魔镇守着六件重装，\n"
    msg = msg.."想要获得这些宝物，就必须首先要杀死这些恶魔，\n"
    msg = msg.."无数的英雄为了获得这些宝物，不惜以自己的生命作为代价，\n"
    msg = msg.."有些人成功了，更多的勇士则倒在了恶魔的脚下，\n"
    msg = msg.."这位英雄，您是否也想去发现这些魔兽的踪迹，\n"
    msg = msg.."给我2000金币，我就能帮您去查看他们的踪影\n\n"
    msg = msg.."#IMAGE1902700018# <@track *01*花20000金币，探查魔兽踪影>\n"
    msg = msg.."　　　　　　　　　  　　　　　　　　　　　　　<@main *01*「返 回」>"

    return msg
end

local map_monster_t = {
    {"死亡神殿", "暗之虹魔教主"},
    {"钳虫巢穴", "暗之沃玛教主"},
    {"深渊魔域", "暗之双头金刚"},
    {"困惑殿堂", "暗之双头血魔"},
    {"堕落坟场", "暗之黄泉教主"},
    {"地狱烈焰", "暗之骷髅精灵"},
}


function track(npc, player)
    lualib:SetPanelSize(npc, 400, 200)
    local msg = "请选择查看的地图\n"
    for i = 1, #map_monster_t do
        msg = msg.."<@track_ex#"..i.." *01*"..map_monster_t[i][1]..">\n"
    end
    msg = msg.."　　　　　　　　　  　　　　　　　　　　　　　<@main *01*「返 回」>"
    return msg
end



function track_ex(npc, player, indexa)
    lualib:SetPanelSize(npc, 400, 200)
    if not lualib:Player_SubGold(player, 20000, false, "查看boss扣金币", "镇魔守将") then
        return "你没有20000金币，无法查看！"
    end

    local indexa = tonumber(indexa)

    local msg = "查询如下:\n"

    local map_guid = lualib:Map_GetMapGuid(map_monster_t[indexa][1])
    local m_num = lualib:Map_GetMonsterCount(map_guid, map_monster_t[indexa][2], true, true)
    if m_num >= 1 then
        msg = msg.."["..map_monster_t[indexa][2].."]已刷新\n"
    else
        msg = msg.."["..map_monster_t[indexa][2].."]未刷新\n"
    end
    msg = msg.."<@main *01*「返 回」>"
    return msg
end


function four_info(npc, player)
    local msg = ""
    msg = msg.."神秘绒丝、魔龙额骨、魔龙骨、魔龙牙都是旷世罕见的稀世珍宝，\n"
    msg = msg.."仅靠一己之力是无法取得这些神奇的宝贝，必须拥有队有的协助\n"
    msg = msg.."在魔龙沼泽,坐标230:187处每30分钟会出现一只特殊的魔龙斜眼\n"
    msg = msg.."届时神秘的魔龙殿通道将会打开，到达魔龙殿，\n"
    msg = msg.."魔龙殿躲藏的妖魔携带着绒丝等珍品，\n"
    msg = msg.."能不能拥有，就看勇士您的造化了！！\n\n"

    msg = msg .."\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
    return msg
end

function goto_map(npc, player)
    local msg = ""
    msg = msg.."盘丝洞是非常危险的地方，交给我50万金币，我可以带你去那里\n"
    msg = msg.."你要在保证生存的前提下，让爆裂蜘蛛的数量在120个以上，\n"
    msg = msg.."你只有3分钟的时间，如果完成要求就可以得到一个“千年蛛丝”\n"
    msg = msg.."不知道你今天的运气如何呢？\n"
    msg = msg.."如果觉得难度太高，也可以给我5万金币，我给你一次掷骰子的机会\n"
    msg = msg.."只要你掷出的点数为6，就可以降低要求，只需要100个以上\n"
    msg = msg.."如果掷出的点数不为6，那你只好再试试运气了\n\n"
    msg = msg.."#IMAGE1902700018# <@gotogoto *01*前往“盘丝洞”>\n"
    msg = msg.."#IMAGE1902700018# <@lucky *01*掷骰子，看运气>\n"

    msg = msg .."\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
    return msg
end

function gotogoto(npc, player)
    --盘丝洞是队伍进入还是单人进入？
    --盘丝洞是什么玩法
    --玩家挑战是天变量吗？

    local gold = 500000
    local gold_n = gold / 10000
    if lualib:Player_IsGoldEnough(player, gold, false) == false then
        local msg = "你没有"..gold_n.."万金币！\n"
        msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
        return msg
    end

    --判断是否已经挑战过

    local player_n1 = lualib:Map_GetPlayerCount(lualib:Map_GetMapGuid("盘丝洞1"), true)
    local player_n2 = lualib:Map_GetPlayerCount(lualib:Map_GetMapGuid("盘丝洞2"), true)
    local player_n3 = lualib:Map_GetPlayerCount(lualib:Map_GetMapGuid("盘丝洞3"), true)
    local player_n4 = lualib:Map_GetPlayerCount(lualib:Map_GetMapGuid("盘丝洞4"), true)


    local map_k_tbl =
    {
        {"盘丝洞1", player_n1},
        {"盘丝洞2", player_n2},
        {"盘丝洞3", player_n3},
        {"盘丝洞4", player_n4},
    }

    table.sort(map_k_tbl, function(a, b) return a[2] < b[2] end)

    if map_k_tbl[1][2] > 0 then
        local msg = "对不起！盘丝洞已经满人！\n"
        msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
        return msg
    end

    local map_k = map_k_tbl[1][1]
    if lualib:SubGold(player, gold, "", "") == true then
        local map_guid = lualib:Map_GetMapGuid(map_k)
        lualib:Map_RemoveMonster(map_guid, "幻影蜘蛛")
        lualib:Map_RemoveMonster(map_guid, "爆裂蜘蛛")
        lualib:Player_MapMove(player, map_k)
    end

    return ""
end

function lucky(npc, player)

    local gold = 50000
    local gold_n = gold / 10000
    if lualib:Player_IsGoldEnough(player, gold, false) == false then
        local msg = "你小子没有"..gold_n.."万金币，怎么能让我帮你减少难度呢？！\n"
        msg = msg .."我可不笨，等你拿来了50000金币再说吧！\n"
        msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
        return msg
    end

    local map = lualib:MapGuid(npc)
    local x, y = lualib:X(npc), lualib:Y(npc)
    local shaizi =
    {
        {"一", 1},
        {"二", 2},
        {"三", 3},
        {"四", 4},
        {"五", 5},
        {"六", 6},
    }
    local shaizi_max = 0

    for i = 1, 3 do
        local r = lualib:GenRandom(1, 6)
        local sz_k = shaizi[r][1]	--骰子KEYNAME
        local sz_n = shaizi[r][2]	--骰子点数
        lualib:Map_GenItemRnd(map, x, y, 4, sz_k, 1, true, 20000)
        shaizi_max = shaizi_max + sz_n
    end
    lualib:AddTimer(npc, lualib:GenTimerId(npc), 4000, 1, "Destroy_SZ")
    lualib:SysWarnMsg(player, "骰子点数："..shaizi_max.."。")

    lualib:SubGold(player, gold, "", "")

    if shaizi_max == 6 then
        lualib:SetInt(player, "gen_zizhu", 100)							----在离开盘丝洞地图时清0
    local msg = "哇，你真厉害，运气那么好，竟然让你投到6，\n"
        msg = msg .."现在你只需要保证爆裂蜘蛛的数量在100以上，\n"
        msg = msg .."你就可以获得“千年蛛丝”了。\n"
        msg = msg .."\n\n　　　　　　　　　　　　　　<@goto_map *01*「返 回」>"
        return msg

    else
        local msg = "你投出的骰子的点数是"..shaizi_max.."\n"
        msg = msg .."这"..gold_n.."万金币，我就收下了！哈哈！！\n"
        msg = msg .."#IMAGE1902700018# <@lucky *01*继续投掷骰子>\n"
        msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
        return msg
    end
    return ""
end

function Destroy_SZ(npc, id)
    local map = lualib:MapGuid(npc)
    local x, y = lualib:X(npc), lualib:Y(npc)
    local item_k = {"一", "二", "三", "四", "五", "六"}

    for i = 1, #item_k do
        local sz_key = item_k[i]
        lualib:Map_ClearItem(map, x, y, 10, sz_key)
    end

end


function web_info(npc, player)
    local msg = ""
    msg = msg.."盘丝洞是非常危险的地方，交给我50万金币，我可以带你去那里\n"
    msg = msg.."你要在保证生存的前提下，让爆裂蜘蛛的数量在120个以上，\n"
    msg = msg.."你只有3分钟的时间，如果完成要求就可以得到一个“千年蛛丝”\n"
    msg = msg.."不知道你今天的运气如何呢？\n"
    msg = msg.."如果觉得难度太高，也可以给我5万金币，我给你一次掷骰子的机会\n"
    msg = msg.."只要你掷出的点数为6，就可以降低要求，只需要26个以上\n"
    msg = msg.."如果掷出的点数不为6，那你只好再试试运气了\n\n"
    msg = msg.."#IMAGE1902700018# <@gotogoto *01*前往“盘丝洞”>\n"
    msg = msg.."#IMAGE1902700018# <@lucky *01*掷骰子，看运气>\n"

    msg = msg .."\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
    return msg
end

function web_gonext(npc, player)
    if lualib:Player_IsTeamLeader(player) == false then
        local msg = "「失败」:请叫你的队长来\n"
        msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
        return msg
    end

    local item_s = "千年蛛丝"
    if lualib:ItemCount(player, item_s) < 1 then
        local msg = "「失败」:你身上没有千年蛛丝！\n"
        msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
        return msg
    end

    local TeamList = lualib:Player_GetTeamList(player)
    for i = 1, #TeamList do
        local distance = lualib:Distance(TeamList[i], npc)
        local person_n = lualib:Name(TeamList[i])
        if distance > 15 then
            local msg = "「条件不够」:队员「"..person_n.."」不在附近，不管他了！\n"
            msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
            return msg
        end
    end

    local map_k1 = "地下宫殿二层1"
    local map_k2 = "地下宫殿二层2"
    local map_k3 = "地下宫殿二层3"
    local map_k4 = "地下宫殿二层4"
    local map1 = lualib:Map_GetMapGuid(map_k1)
    local map2 = lualib:Map_GetMapGuid(map_k2)
    local map3 = lualib:Map_GetMapGuid(map_k3)
    local map4 = lualib:Map_GetMapGuid(map_k4)
    local player_n1 = lualib:Map_GetPlayerCount(map1, true)
    local player_n2 = lualib:Map_GetPlayerCount(map2, true)
    local player_n3 = lualib:Map_GetPlayerCount(map3, true)
    local player_n4 = lualib:Map_GetPlayerCount(map4, true)

    local map_player =
    {
        {player_n1, map_k1},
        {player_n2, map_k2},
        {player_n3, map_k3},
        {player_n4, map_k4},
    }

    table.sort(map_player, function(a, b) return a[1] < b[1] end)

    if map_player[1][1] >= 11 then
        local msg = "「失败」:对不起！里面已经满人！请梢后再试！\n"
        msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
        return msg
    end

    local map_k = map_player[1][2]

    if lualib:TakeItem(player, item_s, 1, "", "") == true then
        lualib:Player_MapMove(player, map_k)
        for i = 1, #TeamList do
            lualib:Player_MapMove(TeamList[i], map_k)
        end
    else
        local msg = "扣除"..item_s.."」失败！\n"
        msg = msg .."\n\n　　　　　　　　　　　　　　<@main *01*「返 回」>"
        return msg
    end

    return ""
end