---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2020/2/27 17:10
---
local lua_path = lualib:IO_GetLuaPath()
local package_path = package.path
package.path = string.format("%s;%s?.lua;%s?", package_path, lua_path, lua_path)
require("system/logic_def_lua")
require("system/serializer")

local xy_table = {
    {"行会争霸场地",28,42,3},
    {"行会争霸场地",70,42,3},
    {"行会争霸场地",48,29,3},
    {"行会争霸场地",48,53,3},
}

function main(npc, player)
    local hanghui = lualib:GetDBStr("Mrrp_行会争霸S1")
    if lualib:GetClientType(player) == 0 then
        local msg ="\n#COLORCOLOR_GREENG#行会争霸-成就王者#COLOREND#\n"
        if hanghui == "" then
            msg = msg.."#COLORCOLOR_RED#当前占领行会：虚位以待\n"
        else

            msg = msg.."#COLORCOLOR_RED#当前占领行会："..hanghui.."\n"
        end

        msg = msg.."#COLORCOLOR_GOLD#1.领地争夺将于每天22:00开启,22:30关门.\n"
        msg = msg.."#COLORCOLOR_PURPLE#2.领地争夺开启后所有已加入行会的玩家均可参与活动.\n"
        msg = msg.."#COLORCOLOR_BLUE#3.领地争夺关门后将地图内非贵行会的玩家清理干净即可获胜.\n"
        msg = msg.."#COLORCOLOR_PURPLE#4.活动开启10分钟后在地图中央刷新行会争霸宝箱.\n"
        msg = msg.."#COLORCOLOR_GREENG#5.获胜行会将获得一天的【行会领地】进入权！\n"
        msg = msg.."#COLORCOLOR_GOLD#6.【行会领地】 每天下午14:00刷新1只超级BOSS!\n"
        msg = msg.."#COLORCOLOR_RED#7.行会争霸场地死亡掉落装备，可以回城，切记\n\n"

        msg = msg.."#OFFSET<X:0,Y:0>##IMAGE1902700015##OFFSET<X:0,Y:-2>#<@chuansong *01*进入场地>　　　#OFFSET<X:0,Y:2>##IMAGE1902700015##OFFSET<X:0,Y:-2>#<@lingdi *01*进入领地> 　　　#OFFSET<X:0,Y:2>##IMAGE1902700034##OFFSET<X:0,Y:-2>#<@Leave *01*离开>\n"
        local SizeX, SizeY = 440,230
        local mingzi = "行会争霸"
        local po_x, po_y = 0,0
        lualib:NPCTalkDetailEx(npc, player, msg, SizeX, SizeY)
        lualib:ShowFormWithContent(player, "脚本表单", "NpcTalk.SetPos("..SizeX..","..SizeY..","..serialize(mingzi)..","..po_x..","..po_y..");")
        return ""
    else
        local msg ="#COLORCOLOR_GREENG#行会争霸-成就王者#COLOREND#\n"
        if hanghui == "" then
            msg = msg.."#COLORCOLOR_RED#当前占领行会：虚位以待\n"
        else

            msg = msg.."#COLORCOLOR_RED#当前占领行会："..hanghui.."\n"
        end

        msg = msg.."#COLORCOLOR_GOLD#1.领地争夺将于每天22:00开启,22:30关门.\n"
        msg = msg.."#COLORCOLOR_PURPLE#2.领地争夺开启后所有已加入行会的玩家均可参与活动.\n"
        msg = msg.."#COLORCOLOR_BLUE#3.领地争夺关门后将地图内非贵行会的玩家清理干净即可获胜.\n"
        msg = msg.."#COLORCOLOR_PURPLE#4.活动开启10分钟后在地图中央刷新行会争霸宝箱.\n"
        msg = msg.."#COLORCOLOR_GREENG#5.获胜行会将获得一天的【行会领地】进入权！\n"
        msg = msg.."#COLORCOLOR_GOLD#6.【行会领地】 每天下午14:00刷新1只超级BOSS!\n"
        msg = msg.."#COLORCOLOR_RED#7.行会争霸场地死亡掉落装备，可以回城，切记\n"

        msg = msg.."#OFFSET<X:0,Y:0>##IMAGE1902700015##OFFSET<X:0,Y:-2>#<@chuansong *01*进入场地>　　　#OFFSET<X:0,Y:2>##IMAGE1902700015##OFFSET<X:0,Y:-2>#<@lingdi *01*进入领地> 　　　#OFFSET<X:0,Y:2>##IMAGE1902700034##OFFSET<X:0,Y:-2>#<@Leave *01*离开>\n"
        local SizeX, SizeY = 440,230
        local mingzi = "行会争霸"
        local po_x, po_y = 0,0
        lualib:NPCTalkDetailEx(npc, player, msg, SizeX, SizeY)
        lualib:ShowFormWithContent(player, "脚本表单", "NpcTalk.SetPos("..SizeX..","..SizeY..","..serialize(mingzi)..","..po_x..","..po_y..");")
        return ""
    end
end

function lingdi(npc, player)
    if lualib:GetFamilyName(player) == "" then
        lualib:MsgBox(player, "您并没有加入行会,无法进入.")
        return main(npc, player)
    end
    if lualib:GetStr("0","Mrrp_行会争霸S0") ~= "" then
        lualib:MsgBox(player, "目前暂时无法进入【行会领地】，请稍后再来！")
        return main(npc, player)
    end
    if lualib:GetFamilyName(player) ~= lualib:GetDBStr("Mrrp_行会争霸S1") then
        lualib:MsgBox(player, "贵行会并未占领行会争霸场地,无法进入【行会领地】.")
        return main(npc, player)
    end
    lualib:Player_MapMove(player,"行会争霸领地")
    return ""
end

function Leave(npc, player)
    return ""
end

function chuansong(npc, player)
    if lualib:GetClientType(player) == 0 then
        local msg ="\n#COLORCOLOR_GREENG#"..lualib:Name(npc).."#COLOREND#\n"
        msg = msg.."#COLORCOLOR_GOLD#1.领地争夺将于每天22:00开启,22:30关门.\n"
        msg = msg.."#COLORCOLOR_GREENG#2.领地争夺开启后所有已加入行会的玩家均可参与活动.\n"
        msg = msg.."#COLORCOLOR_PURPLE#3.领地争夺关门后将地图内非贵行会的玩家清理干净即可获胜.\n"
        msg = msg.."#COLORCOLOR_PURPLE#4.活动开启10分钟后在地图中央刷新行会争霸宝箱.\n"
        msg = msg.."#COLORCOLOR_BLUE#5.获胜行会将获得一天的【行会领地】进入权！\n"
        msg = msg.."#COLORCOLOR_RED#6.【行会领地】每8小时刷新1只超级BOSS!\n\n\n"
        msg = msg.."#OFFSET<X:0,Y:0>##IMAGE1902700015##OFFSET<X:0,Y:-2>#<@chuansong1#1 *01*一号点>　  #OFFSET<X:0,Y:2>##IMAGE1902700015##OFFSET<X:0,Y:-2>#<@chuansong1#2 *01*二号点>　  #OFFSET<X:0,Y:2>##IMAGE1902700015##OFFSET<X:0,Y:-2>#<@chuansong1#3 *01*三号点>　  #OFFSET<X:0,Y:2>##IMAGE1902700015##OFFSET<X:0,Y:-2>#<@chuansong1#4 *01*四号点>\n"
        if lualib:Player_IsGM(player) then
            msg = msg.."<@kaiqi *01*手动开启>              <@guanbi *01*手动关闭>"

        end
        local SizeX, SizeY = 440,280
        local mingzi = "行会争霸"
        local po_x, po_y = 0,0
        lualib:NPCTalkDetailEx(npc, player, msg, SizeX, SizeY)
        lualib:ShowFormWithContent(player, "脚本表单", "NpcTalk.SetPos("..SizeX..","..SizeY..","..serialize(mingzi)..","..po_x..","..po_y..");")
        return ""
    else
        local msg ="#COLORCOLOR_GREENG#"..lualib:Name(npc).."#COLOREND#\n"
        msg = msg.."#COLORCOLOR_GOLD#1.领地争夺将于每天22:00开启,22:30关门.\n"
        msg = msg.."#COLORCOLOR_GREENG#2.领地争夺开启后所有已加入行会的玩家均可参与活动.\n"
        msg = msg.."#COLORCOLOR_PURPLE#3.领地争夺关门后将地图内非贵行会的玩家清理干净即可获胜.\n"
        msg = msg.."#COLORCOLOR_PURPLE#4.活动开启10分钟后在地图中央刷新行会争霸宝箱.\n"
        msg = msg.."#COLORCOLOR_BLUE#5.获胜行会将获得一天的【行会领地】进入权！\n"
        msg = msg.."#COLORCOLOR_RED#6.【行会领地】每8小时刷新1只超级BOSS!\n\n"
        msg = msg.."#OFFSET<X:0,Y:0>##IMAGE1902700015##OFFSET<X:0,Y:-2>#<@chuansong1#1 *01*一号点>　  #OFFSET<X:0,Y:2>##IMAGE1902700015##OFFSET<X:0,Y:-2>#<@chuansong1#2 *01*二号点>　  #OFFSET<X:0,Y:2>##IMAGE1902700015##OFFSET<X:0,Y:-2>#<@chuansong1#3 *01*三号点>　  #OFFSET<X:0,Y:2>##IMAGE1902700015##OFFSET<X:0,Y:-2>#<@chuansong1#4 *01*四号点>\n"
        if lualib:Player_IsGM(player) then
            msg = msg.."<@kaiqi *01*手动开启>              <@guanbi *01*手动关闭>"

        end
        local SizeX, SizeY = 440,280
        local mingzi = "行会争霸"
        local po_x, po_y = 0,0
        lualib:NPCTalkDetailEx(npc, player, msg, SizeX, SizeY)
        lualib:ShowFormWithContent(player, "脚本表单", "NpcTalk.SetPos("..SizeX..","..SizeY..","..serialize(mingzi)..","..po_x..","..po_y..");")
        return ""
    end
end

function guanbi(npc,player)
    lualib:SetStr("0","Mrrp_行会争霸S0", "关门")
    lualib:SetDBStrEx("Mrrp_行会争霸S1", "", 6)

end

function kaiqi(npc,player)
    lualib:GSRunScript("行会争霸入场:on_campaign_start", "")
    lualib:SetStr("0","Mrrp_行会争霸S0", "开启")
    lualib:SetDBStrEx("Mrrp_行会争霸S1", "", 6)
    lualib:SetStr("0","行会争霸临时占领", "")
    local map_guid = lualib:Map_GetMapGuid("行会争霸场地")
    lualib:AddTimer(map_guid, 1, 5000, -1, "hanghuizhengba")
    lualib:DelayCall(map_guid,1000*60*10,"shuanpc","")
    return ""
end

function shuanpc(map_guid)

    lualib:Map_GenNpc(map_guid, "行会争霸宝箱", 50, 41, 0, 3)

end

function hanghuizhengba(timer_id)
    local map_guid = lualib:Map_GetMapGuid("行会争霸场地")
    local map_width = lualib:Map_GetWidth(map_guid)
    local map_height = lualib:Map_GetHeight(map_guid)
    if map_width < map_height then
        map_width = map_height
    end

    --判断地图人数是否小于1
    local Mrrp_guid_table = lualib:Map_GetRegionPlayers(map_guid, 0, 0, map_width, true)
    local Mrrp_guid_table_c = #Mrrp_guid_table
    if Mrrp_guid_table_c < 1 then
        return
    end

    --判断地图是否存在没行会人员
    local result = true
    for i = 1, #Mrrp_guid_table do
        local family_name = lualib:Player_GetStrProp(Mrrp_guid_table[i], lua_role_guild)
        if family_name == "" then
            result = false
            break
        end
    end
    if not result then
        return
    end

    --判断地图是否同一个行会
    local family_name = lualib:Player_GetStrProp(Mrrp_guid_table[1], lua_role_guild)
    local result = true
    for i = 1, #Mrrp_guid_table do
        if not lualib:IsInFamily(Mrrp_guid_table[i], family_name) then
            result = false
            break
        end
    end
    if not result then
        return
    end

    if lualib:GetStr("0","Mrrp_行会争霸S0") == "关门" then
        lualib:SetDBStrEx("Mrrp_行会争霸S1", family_name, 6)
        lualib:SetStr("0","行会争霸临时占领", family_name)
        lualib:SetStr("0","Mrrp_行会争霸S0", "")
        lualib:SysMsg_SendBroadcastMsg("【行会争霸】已被【"..family_name.."】行会占领，本次【行会领地】被【"..family_name.."】行会拿下！", "")
        lualib:DisableTimer(map_guid, 1)
        lualib:GSRunScript("Mrrp_shending1", "")
        return true
    end

    --判断是否已经占领地图
    local shchh = lualib:GetStr("0","行会争霸临时占领")
    if shchh ~= "" then
        local result = true
        for i = 1, #Mrrp_guid_table do
            if lualib:IsInFamily(Mrrp_guid_table[i], shchh) then
                result = false
                break
            end
        end
        if not result then
            return
        end
    end
    lualib:SetStr("0","行会争霸临时占领", family_name)
    lualib:SysMsg_SendBroadcastMsg("【行会争霸】已被【"..family_name.."】行会占领！", "")
    lualib:GSRunScript("Mrrp_shending1", ""..family_name.."")
end

function Mrrp_shending1(player,hh)
    --if lualib:HasTitle(player,29) then
    --lualib:RemoveTitle(player,29)
    --end
    if lualib:GetFamilyName(player) == "" then
        return true
    end
    if lualib:GetFamilyName(player) == hh or lualib:GetFamilyName(player) == lualib:GetDBStr("Mrrp_行会争霸S1") then
        --lualib:AddTitle(player,29)
        --lualib:ApplyTitle(player,29)
        --lualib:SysMsg_SendBottomColor(player, "您获得了一个新的称号[索命阎王],可在角色面板中的称号栏设置显示、隐藏!", 1, 2)
    end
    return true
end

function chuansong1(npc, player,index)
    index = tonumber(index)
    if lualib:GetStr("0","Mrrp_行会争霸S0") == "关门" then
        lualib:MsgBox(player, "大门已经关闭,无法进入.")
        return main(npc, player)
    end
    if lualib:GetStr("0","Mrrp_行会争霸S0") ~= "开启" then
        lualib:MsgBox(player, "活动还未开启,无法进入.")
        return main(npc, player)
    end
    if lualib:GetFamilyName(player) == "" then
        lualib:MsgBox(player, "您并没有加入行会,无法进入.")
        return main(npc, player)
    end
    lualib:Player_MapMoveXY(player,xy_table[index][1],xy_table[index][2],xy_table[index][3],xy_table[index][4])
    --lualib:Player_MapMove(player,"行会争霸场地")
    return ""
end