---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2020/3/2 13:04
---
<form >
<script><![CDATA[
myif_Lfte = {}

myif_Lfte.Init = function(this)
_this = this
for i = 1,#myif_Lfte.tb do
RDItemCtrlSetGUIDataPropByKeyName(this, "道具"..i, myif_Lfte.tb[i].item_n, myif_Lfte.tb[i].shu[1], false)
end

RichEditClear(_this, "规则")
RichEditAppendString(_this, "规则", myif_Lfte.js.."")
for i=1,8 do
ImageSetColor(nil, "转盘系统,特效"..i, 0x00FFFFFF)
end
--MessageBox(MESSAGE_STYLE_OK, #myif_Lfte.zjbiao.."")
for i= 1,4 do
--RDItemCtrlSetGUIDataPropByKeyName(this, "宝箱道具"..i, "武器Z1", 1, false)
RDItemCtrlSetGUIDataPropByKeyName(this, "宝箱道具"..i, myif_Lfte.jlb[i].item[1], myif_Lfte.jlb[i].item[2], false)
local hand = GetWindow(this,"宝箱"..i)
if hand ~= 0 then
local str = ""
str = myif_Lfte.jlb[i].item[1].."*"..myif_Lfte.jlb[i].item[2]
GUI:WndSetHint(hand,str )
end
end
myif_Lfte.ShowLightBk(0)
myif_Lfte.gx()
end

myif_Lfte.gx = function()
script = [[<form default_parent=转盘系统,滚动条>]]
local y = 0
for i = 1,#myif_Lfte.zjbiao do
script = script..[[<richedit id="中奖信息]]..i..[[" x=0 y=]]..y..[[ w=480 h=50 text="]]..myif_Lfte.zjbiao[i][1]..[[【]]..myif_Lfte.zjbiao[i]

[2]..[[】获得:]]..myif_Lfte.zjbiao[i][3]..[["  text_color="BROWN" />	]]
y = y+20
end
script = script..[[</form>]]
GenFormByString(script)

--local swt = GetWindow(nil, "转盘系统,滚动条")
--MessageBox(MESSAGE_STYLE_OK, swt.."!!")
--GUI:ScrollBarSetPos(GetWindow(nil, "转盘系统,滚动条"), 100)

--MessageBox(MESSAGE_STYLE_OK, myif_Lfte.sj.."!!")

RichEditClear(_this, "已转次数")
RichEditAppendString(_this, "已转次数", "活动时间已抽取:"..myif_Lfte.cs.."次")
RichEditClear(_this, "剩余时间")
RichEditAppendString(_this, "剩余时间", "剩余时间:"..GetLeaveTimeString(myif_Lfte.sj))
EditSetTextM(_this, "元宝", tostring(myif_Lfte.yb))
for i = 1,#myif_Lfte.jlb do
local _GUIHandle = GetWindow(nil, "转盘系统,编辑框时间"..i)
if _GUIHandle ~= 0 then
local stt = ""
if myif_Lfte.jlb[i].ci <= myif_Lfte.cs then
if myif_Lfte.jlb[i].l > 0 then
stt = "已领取"
WndSetTextColorM(_GUIHandle,nil,MakeARGB(255, 205, 180, 98))
--GUI:WndSetVisible(_Handle1, false)
ImageSetImageID(nil,"转盘系统,宝箱"..i,1854500005)
else
stt = "可领取"
WndSetTextColorM(_GUIHandle,nil,MakeARGB(255, 0, 204, 0))
--GUI:WndSetVisible(_Handle1, true)
ImageSetImageID(nil,"转盘系统,宝箱"..i,1854500002)

end
else
stt = "抽"..(myif_Lfte.jlb[i].ci - myif_Lfte.cs).."次可领"

end
GUI:EditSetTextM(_GUIHandle,""..stt)
end
end
end

myif_Lfte.ShowLightBk = function(idx)
local img = GetWindow(nil, "转盘系统,特效"..idx)
if img == 0 then
for i=1,18 do
ImageSetAlpha(nil, "转盘系统,特效"..i, 0)--0
end
else
ImageSetAlpha(img, nil, 255)
end
for i = 1,3 do
WndSetEnableM(nil, "转盘系统,按钮"..i, true)
end
end

myif_Lfte.OnTimer2 = function()
--t.CurRollPos = t.CurRollPos + 1

myif_Lfte.CurShowPos = myif_Lfte.CurShowPos + 1
if myif_Lfte.CurShowPos > 18 then
myif_Lfte.CurShowPos = 1
lun = lun + 1
end

for i=1,18 do
ImageSetAlpha(nil, "转盘系统,特效"..i, 0)
end

ImageSetAlpha(nil, "转盘系统,特效"..myif_Lfte.CurShowPos, 255)

if lun >= 5 and myif_Lfte.CurShowPos == myif_Lfte.zhong then
WndDelTimer(nil, "转盘系统", 333)
UI:Lua_SubmitForm("转盘系统", "uqdd", myif_Lfte.zhong.."")
myif_Lfte.ShowLightBk(myif_Lfte.CurShowPos)
end

end

myif_Lfte.zhuan = function()
myif_Lfte.CurShowPos = 0
lun = 0
--myif_Lfte.zhong=5
WndAddTimer(nil, "转盘系统", 333, 100, "myif_Lfte.OnTimer2")
for i = 1,3 do
WndSetEnableM(nil, "转盘系统,按钮"..i, false)
end

end

myif_Lfte.OK = function(this)
local num  = WndGetProperty(this, nil, "num")
UI:Lua_SubmitForm("转盘系统", "Cishu", num)
end

function myif_Lfte.MoveOut(this)
local param = tonumber(WndGetParam(this))
WndSetVisible(nil, "转盘系统,宝箱选择框"..param,false)
end

function myif_Lfte.MoveIn(this)
local param = tonumber(WndGetParam(this))
WndSetVisible(nil, "转盘系统,宝箱选择框"..param,true)
end

function myif_Lfte.LQ(this)
local param = tostring(WndGetParam(this))
UI:Lua_SubmitForm("转盘系统", "Lingqu", param)
end

myif_Lfte.mai = function(this)
local param = WndGetProperty(this, nil, "num")
UI:Lua_SubmitForm("转盘系统", "mai", param)
end

myif_Lfte.Gb = function(this)
WndClose(nil, "转盘系统")
end



]]></script>
<dialog id="转盘系统" x="150" y="80" w="750" h="470" image="1801100001" close="false"  center="true"  fitsize="true" OnInit=myif_Lfte.Init >
<image id="美女图右" image="1801000012" x="30" y="70" w="330" h="320" fitsize=true />
<richedit id="剩余时间" x=125 y=77 w=150 h=50 text="" text_color="GREENG" />
<richedit id="已转次数" x=125 y=353 w=150 h=50 text="" text_color="RED" />
<richedit id="活动规则" x=343 y=30 w=150 h=50 text="玩家抽奖" font=SIMLI18 text_color="GREENG" />
<button id="关闭" x="693" y="35" image="1803700030"  OnLButtonClick=myif_Lfte.Gb />
<richedit id="规则" x=30 y=395 w=320 h=50 text="" text_color="" />

<image id="左边特效" x="85" y="120" w=300 h=285  type=animate image=1680000000,200 fitsize=true/>
<image id="材料框1" x=56 y=108 w=45 h=45 type=normal image=1910300017 fitsize=true/>
<image id="材料框2" x=56 y=155 w=45 h=45 type=normal image=1910300017 fitsize=true/>
<image id="材料框3" x=56 y=202 w=45 h=45 type=normal image=1910300017 fitsize=true/>
<image id="材料框4" x=56 y=249 w=45 h=45 type=normal image=1910300017 fitsize=true/>
<image id="材料框5" x=56 y=296 w=45 h=45 type=normal image=1910300017 fitsize=true/>
<image id="材料框6" x=103 y=108 w=45 h=45 type=normal image=1910300017 fitsize=true/>
<image id="材料框7" x=150 y=108 w=45 h=45 type=normal image=1910300017 fitsize=true/>
<image id="材料框8" x=197 y=108 w=45 h=45 type=normal image=1910300017 fitsize=true/>
<image id="材料框9" x=244 y=108 w=45 h=45 type=normal image=1910300017 fitsize=true/>
<image id="材料框10" x=291 y=108 w=45 h=45 type=normal image=1910300017 fitsize=true/>
<image id="材料框11" x=291 y=155 w=45 h=45 type=normal image=1910300017 fitsize=true/>
<image id="材料框12" x=291 y=202 w=45 h=45 type=normal image=1910300017 fitsize=true/>
<image id="材料框13" x=291 y=249 w=45 h=45 type=normal image=1910300017 fitsize=true/>
<image id="材料框14" x=291 y=296 w=45 h=45 type=normal image=1910300017 fitsize=true/>
<image id="材料框15" x=244 y=296 w=45 h=45 type=normal image=1910300017 fitsize=true/>
<image id="材料框16" x=197 y=296 w=45 h=45 type=normal image=1910300017 fitsize=true/>
<image id="材料框17" x=150 y=296 w=45 h=45 type=normal image=1910300017 fitsize=true/>
<image id="材料框18" x=103 y=296 w=45 h=45 type=normal image=1910300017 fitsize=true/>
<image id="中间部分" x=135 y=165 w=120 h=120 type=normal image=1853700011 fitsize=true/>


<image id="特效1"  image=1909100006,200 x=51 y=101 w=54 h=54 type=animate fitsize="true" />
<image id="特效2"  image=1909100006,200 x=98 y=101 w=54 h=54 type=animate fitsize="true" />
<image id="特效3"  image=1909100006,200 x=145 y=101 w=54 h=54 type=animate fitsize="true" />
<image id="特效4"  image=1909100006,200 x=192 y=101 w=54 h=54 type=animate fitsize="true" />
<image id="特效5"  image=1909100006,200 x=239 y=101 w=54 h=54 type=animate fitsize="true" />
<image id="特效6"  image=1909100006,200 x=286 y=101 w=54 h=54 type=animate fitsize="true" />
<image id="特效7"  image=1909100006,200 x=286 y=148 w=54 h=54 type=animate fitsize="true" />
<image id="特效8"  image=1909100006,200 x=286 y=195 w=54 h=54 type=animate fitsize="true" />
<image id="特效9"  image=1909100006,200 x=286 y=242 w=54 h=54 type=animate fitsize="true" />
<image id="特效10"  image=1909100006,200 x=286 y=289 w=54 h=54 type=animate fitsize="true" />
<image id="特效11"  image=1909100006,200 x=239 y=289 w=54 h=54 type=animate fitsize="true" />
<image id="特效12"  image=1909100006,200 x=192 y=289 w=54 h=54 type=animate fitsize="true" />
<image id="特效13"  image=1909100006,200 x=145 y=289 w=54 h=54 type=animate fitsize="true" />
<image id="特效14"  image=1909100006,200 x=98 y=289 w=54 h=54 type=animate fitsize="true" />
<image id="特效15"  image=1909100006,200 x=51 y=289 w=54 h=54 type=animate fitsize="true" />
<image id="特效16"  image=1909100006,200 x=51 y=242 w=54 h=54 type=animate fitsize="true" />
<image id="特效17"  image=1909100006,200 x=51 y=195 w=54 h=54 type=animate fitsize="true" />
<image id="特效18"  image=1909100006,200 x=51 y=148 w=54 h=54 type=animate fitsize="true" />

<itemctrl id="道具1" x=61 y=113 w=35 h=35 init_item="" use_back=false fitsize="false" />
<itemctrl id="道具2" x=108 y=113 w=35 h=35 init_item="" use_back=false fitsize="false" />
<itemctrl id="道具3" x=155 y=113 w=35 h=35 init_item="" use_back=false fitsize="false" />
<itemctrl id="道具4" x=202 y=113 w=35 h=35 init_item="" use_back=false fitsize="false" />
<itemctrl id="道具5" x=249 y=113 w=35 h=35 init_item="" use_back=false fitsize="false" />
<itemctrl id="道具6" x=296 y=113 w=35 h=35 init_item="" use_back=false fitsize="false" />
<itemctrl id="道具7" x=296 y=160 w=35 h=35 init_item="" use_back=false fitsize="false" />
<itemctrl id="道具8" x=296 y=207 w=35 h=35 init_item="" use_back=false fitsize="false" />
<itemctrl id="道具9" x=296 y=254 w=35 h=35 init_item="" use_back=false fitsize="false" />
<itemctrl id="道具10" x=296 y=301 w=35 h=35 init_item="" use_back=false fitsize="false" />
<itemctrl id="道具11" x=249 y=301 w=35 h=35 init_item="" use_back=false fitsize="false" />
<itemctrl id="道具12" x=202 y=301 w=35 h=35 init_item="" use_back=false fitsize="false" />
<itemctrl id="道具13" x=155 y=301 w=35 h=35 init_item="" use_back=false fitsize="false" />
<itemctrl id="道具14" x=108 y=301 w=35 h=35 init_item="" use_back=false fitsize="false" />
<itemctrl id="道具15" x=61 y=301 w=35 h=35 init_item="" use_back=false fitsize="false" />
<itemctrl id="道具16" x=61 y=254 w=35 h=35 init_item="" use_back=false fitsize="false" />
<itemctrl id="道具17" x=61 y=207 w=35 h=35 init_item="" use_back=false fitsize="false" />
<itemctrl id="道具18" x=61 y=160 w=35 h=35 init_item="" use_back=false fitsize="false" />
<richedit id="奖池标题1" x=160 y=190 w=80 h=50 text="当前奖池" font=SIMLI18 text_color="GREENG" />
<richedit id="奖池标题2" x=177 y=235 w=80 h=50 text="元宝" font=SIMLI18 text_color="GREENG" />
<edit id="元宝" x=170 y=208 w=50 h=20 text="" align="center" text_color="PURPLE" />

<image id="信息背景" x=365 y=70 w=355 h=180 type=normal image=1852700013 fitsize=true/>

<richedit id="中奖信息" x=500 y=67 w=480 h=50 text="中奖信息" font=SIMLI18 text_color="BROWN" />
<wnd id="滚动条" image="1906300010,1906300009,1906300018,1906300014" x=415 y=95 w=280 h=140 scroll=true >

</wnd>

<button id="按钮1" x="400" y="250" w="50" h="50" num="1" enable="true" image="1910000103" text="抽奖一次" text_color="GOLD" OnLButtonClick="myif_Lfte.OK" />
<button id="按钮2" x="500" y="250" w="50" h="50" num="10" enable="true" image="1910000103" text="抽奖十次" text_color="GOLD" OnLButtonClick="myif_Lfte.OK" />
<button id="按钮3" x="600" y="250" w="50" h="50" num="50" enable="true" image="1910000103" text="抽奖五十次" text_color="GOLD" OnLButtonClick="myif_Lfte.OK" />

<image id="材料底部1" x=364 y=287 w=85 h=85 type=normal image=1802900063 fitsize=true/>
<image id="材料底部2" x=454 y=287 w=85 h=85 type=normal image=1802900063 fitsize=true/>
<image id="材料底部3" x=544 y=287 w=85 h=85 type=normal image=1802900063 fitsize=true/>
<image id="材料底部4" x=634 y=287 w=85 h=85 type=normal image=1802900063 fitsize=true/>
<richedit id="温馨提示" x=430 y=400 w=480 h=50 text="温馨提醒:纯属娱乐,切勿过度" font=SIMLI18 text_color="GOLD" />

<image id="宝箱1" image="1910000084" x="368" y="347" w="75" h="20" fitsize="true" param="1" OnMouseIn=myif_Lfte.MoveIn OnMouseOut=myif_Lfte.MoveOut revmsg="true" OnLButtonClick="myif_Lfte.LQ" />
<image id="宝箱2" image="1910000084" x="458" y="347" w="75" h="20" fitsize="true" param="2" OnMouseIn=myif_Lfte.MoveIn OnMouseOut=myif_Lfte.MoveOut revmsg="true" OnLButtonClick="myif_Lfte.LQ" />
<image id="宝箱3" image="1910000084" x="548" y="347" w="75" h="20" fitsize="true" param="3" OnMouseIn=myif_Lfte.MoveIn OnMouseOut=myif_Lfte.MoveOut revmsg="true" OnLButtonClick="myif_Lfte.LQ" />
<image id="宝箱4" image="1910000084" x="638" y="347" w="75" h="20" fitsize="true" param="4" OnMouseIn=myif_Lfte.MoveIn OnMouseOut=myif_Lfte.MoveOut revmsg="true" OnLButtonClick="myif_Lfte.LQ" />

<edit id="编辑框时间1" x="367" y="343" w="75" h="20" align="center" text_color="SKYBLUE" enable="false"  text="" />
<edit id="编辑框时间2" x="457" y="343" w="75" h="20" align="center" text_color="SKYBLUE" enable="false"  text="" />
<edit id="编辑框时间3" x="547" y="343" w="75" h="20" align="center" text_color="SKYBLUE" enable="false"  text="" />
<edit id="编辑框时间4" x="637" y="343" w="75" h="20" align="center" text_color="SKYBLUE" enable="false"  text="" />

<itemctrl id="宝箱道具1" x=390 y=307 w=35 h=35 init_item="" use_back=true fitsize="false" />
<itemctrl id="宝箱道具2" x=480 y=307 w=35 h=35 init_item="" use_back=true fitsize="false" />
<itemctrl id="宝箱道具3" x=570 y=307 w=35 h=35 init_item="" use_back=true fitsize="false" />
<itemctrl id="宝箱道具4" x=660 y=307 w=35 h=35 init_item="" use_back=true fitsize="false" />


</dialog>
</form>