---dd
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tyf.
--- DateTime: 2020/2/27 16:23
---
local lua_path = lualib:IO_GetLuaPath()
local package_path = package.path
package.path = string.format("%s;%s?.lua;%s?", package_path, lua_path, lua_path)
require("system/logic_def_lua")
require("form/Common")

local Martial = {
    "卸岭门",
    "力士门",
    "寻龙门",
    "摸金门",
    "搬山门",
    "分甲门"
}

local mapName = {
    {"龙城",295,339},
    {"巫山城",376,283},
    {"日月门",198,209},
    {"蛮荒城",198,169},
    {"镇魔城",206,176}
}

function main()
    lualib:AddScheduled(100050, "门派入侵", 5, {"15:15:00"}, "invade", "")
    lualib:AddScheduled(100050, "门派入侵", 5, {"15:20:00"}, "invade", "")
    lualib:AddScheduled(100050, "门派入侵", 5, {"15:25:00"}, "invade", "")
end

function invade()
    local mapRandom = lualib:GenRandom(1,#mapName)          --随机地图
    local map = mapName[mapRandom][1]                       --地图名称
    local mapGuid = lualib:Map_GetMapGuid(map)              --地图GUID
    local random = lualib:GenRandom(1,6)                    --随机门派
    lualib:SetDBNum("mapRandom",mapRandom)
    lualib:SetDBNum("mpRandom",random)                --保存随机门派
    lualib:SysMsg_SendBroadcastMsg(tostring(mapRandom)..":"..tostring(map),"门派入侵")
    lualib:SysMsg_SendBroadcastColor(tostring(Martial[random]).."反贼入侵"..tostring(map).."请与"..tostring(Martial[random]).."成员组队前往"..map.."中心100范围内寻找NPC进入!!十分钟后NPC消失","系统公告",1,12)
    lualib:SysMsg_SendBroadcastColor(tostring(Martial[random]).."反贼入侵"..tostring(map).."请与"..tostring(Martial[random]).."成员组队前往"..map.."中心100范围内寻找NPC进入!!十分钟后NPC消失","系统公告",1,12)
    lualib:SysMsg_SendBroadcastColor(tostring(Martial[random]).."反贼入侵"..tostring(map).."请与"..tostring(Martial[random]).."成员组队前往"..map.."中心100范围内寻找NPC进入!!十分钟后NPC消失","系统公告",1,12)

    for i=1,10 do
        if lualib:Map_GenNpc(mapGuid,"门派入侵",mapName[mapRandom][2],mapName[mapRandom][3],100,1) == "" then       --刷新npc
            lualib:SysMsg_SendBroadcastMsg("刷新npc失败", "")
        end
    end
    lualib:AddTimerEx(mapGuid,1008611,1000*60,1,"delNpc",tostring(mapRandom))
    return ""
end

function delNpc(mapGuid)
    local random = lualib:GetDBNum("mapRandom")
    lualib:SysMsg_SendBroadcastMsg(tostring(random)..":".."清除成功","门派入侵")
    lualib:Map_ClearNpc(mapGuid,mapName[random][2],mapName[random][3],200,"门派入侵")
end