---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2020/2/29 16:58
---

local Martial = {
    "卸岭门",
    "力士门",
    "寻龙门",
    "摸金门",
    "搬山门",
    "分甲门"
}



function main(npc,player)
    local random = lualib:GetDBNum("mpRandom")
    local team = lualib:Player_GetTeamList(player)  --队伍列表
    local num = 0
    local name = lualib:Name(player)

    if not lualib:Player_HasTeam(player) then                                   --是否有队伍
        lualib:SysMsg_SendPromptMsg(player,"请先组队再来这里！")
        return ""
    end

    if not lualib:Player_IsTeamLeader(player) then                              --是否是队长点击
        lualib:SysMsg_SendPromptMsg(player,"只有队长才能带领进入！")
        return ""
    end

    for i,v in pairs(team) do
        if Martial[tonumber(lualib:GetInt(v,"menpai"))] == Martial[random] then
            num = 1
            break
        end
    end

    if num ~= 1 then                                                            --队伍中是否有对应门派的人员
        lualib:SysMsg_SendPromptMsg(player,"队伍需要有"..tostring(Martial[random]).."门派中的人员！")
        return ""
    end

    local dgnMap = lualib:Map_CreateDgn("入侵", true,1*60*60)
    if dgnMap  == "" then
        lualib:SysMsg_SendPromptMsg(player,"地图创建失败！请联系管理员!")
        return ""
    end

    for i,v in pairs(team) do
        local distance =  lualib:Distance(npc,v)
        local level = lualib:Level(v)
        if level < 35 then
            lualib:SysMsg_SendPromptMsg(player,"您的队友小于35级，无法进入副本！！")
            return ""
        end
        if distance > 8 then
            lualib:SysMsg_SendPromptMsg(player,"队友距离NPC距离太远，无法进入副本！！")
            return ""
        end

    end

    for i,v in pairs(team) do
        lualib:Player_SetDgnTicket(v,dgnMap)
        lualib:Map_JumpXY(dgnMap,v,184,176,2)
    end

    if not lualib:Npc_Remove(npc) then
        lualib:Error("npc移除失败！")
        return ""
    end

    lualib:SysMsg_SendBroadcastColor("玩家【"..name.."】带领的队伍进入了门派营地击杀反贼！！","系统公告",1,12)
    return ""
end