---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tyf.
--- DateTime: 2020/3/3 13:18
---
function on_map_create(map)
    lualib:SetInt(map,"bossAppear",0)
    lualib:SetInt(map,"monsterNum",20)
    lualib:Map_BatchGenMonster(map,"门派反贼",20,false)
    lualib:AddTrigger(map, lua_trigger_enter_map, "on_enter_map")   --玩家进入地图时回调
    lualib:AddTrigger(map, lua_trigger_leave_map, "on_leave_map")   --玩家离开地图时回调
    lualib:AddTrigger(map, lua_trigger_monster_post_die , "on_post_monster_die")    --怪物死亡后回调
end

function on_enter_map(player)
    lualib:MsgBox(player,"请先清空地图内20只小怪！！清空之后会出现Boss！boss出现时会出现提示内容注意查看！")

end

function on_post_monster_die(monster,killer)
    local team = lualib:Player_GetTeamList(killer)
    local map = lualib:MapGuid(monster)
    local monsterCount = lualib:Map_GetMonsterCount(map,"",true,true)
    if lualib:GetInt(map,"bossAppear") ~= 1 then
        if monsterCount == 0 then
            lualib:Map_BatchGenMonster(map,"反贼统领",1,false)
            lualib:SysMsg_SendCenterMsg(3,"boss出现在地图中请玩家尽快进行击杀！！！",killer)
            lualib:SetInt(map,"bossAppear",1)
        end
    end
    lualib:SetInt(map,"monsterNum",lualib:GetInt(map,"monsterNum") - 1)
    local num = lualib:GetInt(map,"monsterNum")
    for i,v in pairs(team) do
        if num > 0 then
            lualib:SysPromptMsg(v,"当前剩余小怪："..tostring(num).."只")
        end
    end
    return ""
end

function on_leave_map(player)

end