---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ya.
--- DateTime: 2020/7/21 15:12
---

local timeNum =  0
function receive(player)
    if lualib:GetDBNum("treasureChest") == 1 then
        lualib:Player_MapMoveXY(player,"酷跑地图",306,287,3)
    else
        lualib:MsgBox(player,"活动尚未开始！")
    end
    return ""
end

function treasureChestTimer()
    local startTimeStr = lualib:GetConstVar("StartServerTime")      --开区时间字符串
    local startTime = lualib:Str2Time(startTimeStr)                 --开区时间
    local currentTimeStr = lualib:Now()                             --当前时间字符串
    local currentTime = lualib:Str2Time(currentTimeStr)                             --当前时间
    local activit = lualib:Str2Time("2020-05-01 22:15:00")                             --指定开始时间
    local map = lualib:Map_GetMapGuid("宝箱活动地图")
    if (currentTime - activit) % (24 * 60 * 60) == 0 and currentTime > startTime then
        lualib:SetDBNum("treasureChest",1)
        lualib:SysMsg_SendBroadcastMsg("激情宝箱活动开始，从弹窗加入或是从右上角活动中的第三个活动进入！！！", "激情宝箱")
        lualib:SysMsg_SendBroadcastMsg("激情宝箱活动开始，从弹窗加入或是从右上角活动中的第三个活动进入！！！", "激情宝箱")
        lualib:SysMsg_SendBroadcastMsg("激情宝箱活动开始，从弹窗加入或是从右上角活动中的第三个活动进入！！！", "激情宝箱")
        if lualib:Map_GetMonsterCount(map, "宝箱使者", true, true) == 0 then
            lualib:Map_GenMonster(map,50,55,1,1,"宝箱使者",1,false)
        end
        lualib:GSRunScript("sendInviteMail",currentTimeStr)
        timeNum = 0
    end
    return ""
end

function treasureChestOver()
    timeNum = timeNum + 1
    if timeNum == 120 then
        lualib:DisableTimer("0",20200720)
        lualib:SetDBNum("treasureChest",0)
        lualib:SysMsg_SendBroadcastMsg("跑酷活动入口关闭！！！", "跑酷活动")
        lualib:SysMsg_SendBroadcastMsg("跑酷活动入口关闭！！！", "跑酷活动")
        lualib:SysMsg_SendBroadcastMsg("跑酷活动入口关闭！！！", "跑酷活动")
    end
    return ""
end

function sendInviteMail(player, param)
    lualib:SysMsg_SendTriggerMsg(player, "你收到了\"跑酷竞速\"邀请！")
    local msg = "跑酷入场开始了！活动前六名获得元宝和经验，活动两分钟后结束，你要参加么？\n \n"
    msg = msg.."<@enter *01*我要进入>\n"
    msg = msg.."<@leave *02*我很忙>"
    lualib:NPCTalk(player, msg)
end

function enter(player)
    local map_key_name = "龙城"

    if lualib:HasBuff(player,"摆摊") then
        lualib:SysWarnMsg(player,"你当前处于摆摊状态，无法传送")
        return false
    end

    if not lualib:Player_MapMoveXY(player,"酷跑地图",306,287,1) then
        lualib:SysMsg_SendWarnMsg(player, "")
    end
    return ""
end