---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ya.
--- DateTime: 2019/11/4 21:16
---

local necklaceType = {
    {"战神坠饰","战神项链",3,5},
    {"真魂道链","真魂项链",3,5},
    {"圣魔法链","圣魔项链",3,5},
    {"火龙战链","火龙战链",3,5},
    {"火龙道链","火龙道链",3,5},
    {"火龙魔链","火龙魔链",3,5},
    {"盛世道链","冰龙道链",3,5},
    {"盛世战链","冰龙战链",3,5},
    {"盛世魔链","冰龙魔链",3,5},
    {"龙城战链","完美战链",4,5},
    {"龙城道链","完美道链",4,5},
    {"龙城魔链","完美魔链",4,5}
}

function main(npc, player)

    local msg = "#COLORCOLOR_GREENG#您当前所处服务为:【#COLORCOLOR_RED#幸运服务#COLOREND##COLORCOLOR_GREENG#】#COLOREND#\n\n"
    for i=1,#necklaceType do
        msg = msg.."#IMAGE1902700041# <@InfoItemRefine#"..i.." *01*【"..necklaceType[i][1].."】>#COLOREND#  "
        if i%3==0 then
            msg = msg.."\n\n"
        end
    end

    return msg

end
-------------------------------------------------------------------------------------------幸运项链
function InfoItemRefine(npc, player,num)
    num = tonumber(num)
    local msg = "\n"
    msg = msg.."#IMAGE<ID:1902700017>#<@xingyun#1#"..num.." *01*提升幸运1>#COLORCOLOR_RED#需要当前幸运为0，每次消耗150元宝#COLOREND#\n\n"
    msg = msg.."#IMAGE<ID:1902700017>#<@xingyun#2#"..num.." *01*提升幸运2>#COLORCOLOR_RED#需要当前幸运为1，每次消耗250元宝#COLOREND#\n\n"
    msg = msg.."#IMAGE<ID:1902700017>#<@xingyun#3#"..num.." *01*提升幸运3>#COLORCOLOR_RED#需要当前幸运为2，每次消耗350元宝#COLOREND#\n\n"
    msg = msg.."#COLORCOLOR_GREENG#温馨提示：升级幸运+3项链会随机出现1-3点暴击属性，但是有概率失败哦！#COLOREND#\n"
    --msg = msg.."#OFFSET<X:0,Y:0>##COLORCOLOR_BROWN#▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂#COLOREND#\n"
    msg = msg.."                                            #IMAGE<ID:1902700019>#<@main *01*「返回」>"
    return msg
end

function xingyun(npc, player, leixing,num)
    leixing = tonumber(leixing)
    num = tonumber(num)

    local xingyun_tb =
    {
        {150, 0, 2},
        {250, 1, 3},
        {350, 2, 5},
    }
    local item_guid = lualib:Player_GetItemGuid(player, 9)
    if item_guid == "" then
        return "你没有装备【"..necklaceType[num][1].."】，不能使用添加幸运属性！\n \n#IMAGE<ID:1902700019>#<@InfoItemRefine#"..num.." *01*「返回」>"
    end
    if lualib:KeyName(item_guid) ~= necklaceType[num][2] then
        return "你没有装备【"..necklaceType[num][1].."】，不能使用添加幸运属性！\n \n#IMAGE<ID:1902700019>#<@InfoItemRefine#"..num.." *01*「返回」>"
    end

    local luck_curse = lualib:Equip_GetLuckCurse("", item_guid)
    local xingyun = 0
    for i=0,5 do
        local t = lualib:Equip_GetQualProp(player,item_guid,i)
        if t[0] == 50 then
            xingyun = xingyun + t[1]
        end
    end

    local item_t = lualib:Item_DataRow(lualib:KeyName(item_guid)) --根据物品KeyName取得该物品的配置表结构.
    if item_t["LC"] > 0 then
        xingyun = xingyun + item_t["LC"]
    end

    if (luck_curse + xingyun) ~= xingyun_tb[tonumber(leixing)][2] then
        return "需要您的项链幸运为"..xingyun_tb[tonumber(leixing)][2].."，您的项链不符合要求！\n \n#IMAGE<ID:1902700019>#<@InfoItemRefine#"..num.." *01*「返回」>"
    end

    if not lualib:Player_IsIngotEnough(player, xingyun_tb[tonumber(leixing)][1], false) then
        return "元宝不足！请充值后在来提升幸运属性！\n \n#IMAGE<ID:1902700019>#<@InfoItemRefine#"..num.." *01*「返回」>"
    end

    if not lualib:Player_SubIngot(player, xingyun_tb[tonumber(leixing)][1], false, "扣元宝：提升幸运属性1", player) then
        return "扣除元宝失败！\n \n#IMAGE<ID:1902700019>#<@InfoItemRefine#"..num.." *01*「返回」>"
    end

    local luck = luck_curse + 1
    if lualib:GenRandom(1, xingyun_tb[tonumber(leixing)][3]) == 2 then
        local player_name = lualib:Name(player)
        if lualib:Equip_SetLuckCurse(player, item_guid, luck) == false then
            lualib:SysMsg_SendWarnMsg(player, "提升幸运属性失败！")
            return "提升幸运属性失败！\n \n<@InfoItemRefine#"..num.." *01*「返回」>"
        end
        if leixing == 3 then
            for i=0,5 do
                local t = lualib:Equip_GetQualProp(player,item_guid,i)
                if t[1] == 0 then
                    local dian = 1
                    if lualib:GenRandom(1,500) == 1 then
                        dian = 3
                    elseif lualib:GenRandom(1,100) == 1 then
                        dian = 2
                    end
                    lualib:Equip_SetQualProp(player,item_guid,i,49,dian) --设置暴击属性
                    break
                end
            end
        end
        lualib:Item_NotifyUpdate(player,item_guid) --向物品的主人通知物品属性更新.
        lualib:SysMsg_SendBroadcastMsg("玩家["..player_name.."]".."在[龙城]将项链幸运提升了"..luck.."点！如果您也有需求，请到龙城找到幸运之家", "")
        lualib:SysMsg_SendBroadcastMsg("玩家["..player_name.."]".."在[龙城]将项链幸运提升了"..luck.."点！如果您也有需求，请到龙城找到幸运之家", "")
        lualib:SysMsg_SendBroadcastMsg("玩家["..player_name.."]".."在[龙城]将项链幸运提升了"..luck.."点！如果您也有需求，请到龙城找到幸运之家", "")
        return "恭喜您的项链幸运属性提升了"..luck.."点！\n \n<@InfoItemRefine#"..num.." *01*「返回」>"
    end
    return "很遗憾，您这次的幸运属性提升失败，下次可能会成功！加油！\n \n#IMAGE<ID:1902700019>#<@InfoItemRefine#"..num.." *01*「返回」>"
end

