---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ya.
--- DateTime: 2020/7/20 19:48
---

local parkourReward = {     --奖励元宝数量，奖励经验数量
    {800,10000000},
    {600,8000000},
    {500,6000000},
    {400,5000000},
    {300,3000000},
    {200,2000000},
}

function main(npc, player)
    local msg = "#COLORCOLOR_GOLD#                   跑酷奖励领取                   #COLOREND#\n"
    msg = msg.."#COLORCOLOR_SKYBLUE# --------------------------------------------------------------------#COLOREND#\n\n"
    msg = msg.."#COLORCOLOR_RED# 点击领取，排名前六的可获得一下奖励奖励：#COLOREND#\n\n"
    msg = msg.."#COLORCOLOR_SKYBLUE# 【第一名:800元宝1000万经验】 获奖："..lualib:GetDBStr("parkour1").."#COLOREND#\n"
    msg = msg.."#COLORCOLOR_SKYBLUE# 【第二名:600元宝800 万经验】 获奖："..lualib:GetDBStr("parkour2").."#COLOREND#\n"
    msg = msg.."#COLORCOLOR_SKYBLUE# 【第三名:500元宝600 万经验】 获奖："..lualib:GetDBStr("parkour3").."#COLOREND#\n"
    msg = msg.."#COLORCOLOR_SKYBLUE# 【第四名:400元宝500 万经验】 获奖："..lualib:GetDBStr("parkour4").."#COLOREND#\n"
    msg = msg.."#COLORCOLOR_SKYBLUE# 【第五名:300元宝300 万经验】 获奖："..lualib:GetDBStr("parkour5").."#COLOREND#\n"
    msg = msg.."#COLORCOLOR_SKYBLUE# 【第六名:200元宝200 万经验】 获奖："..lualib:GetDBStr("parkour6").."#COLOREND#\n"
    msg = msg.."#IMAGE<ID:1902700042>#<@receive *01*【领取奖励】>\n"
    lualib:NPCTalkDetailEx(npc, player, msg, 500, 240)
    return""
end

function receive(npc,player)
    local num = 0               --排名
    local name = lualib:KeyName(player)

    for i=1,6 do
        if lualib:GetDBStr("parkour"..i) == "无人获取" then
            lualib:SetDBStr("parkour"..i,name)
            num = i
            break
        end
    end

    if num == 0 then
        lualib:MsgBox(player,"已经全部领完了！！！")
        return ""
    end
    if lualib:Level(player) < 75 then
        lualib:AddExp(player,parkourReward[num][2],"跑酷奖励经验","Ya酷跑奖励")
    else
        lualib:SysPromptMsg(player,"玩家超过75级不获得经验！！！")
    end
    lualib:AddIngot(player,parkourReward[num][1],"跑酷奖励添加元宝","Ya酷跑奖励")
    lualib:SysMsg_SendBroadcastMsg("恭喜玩家【"..name.."】获得跑酷第"..num.."名奖励！！！！","跑酷奖励")
    lualib:SysMsg_SendBroadcastMsg("恭喜玩家【"..name.."】获得跑酷第"..num.."名奖励！！！！","跑酷奖励")
    lualib:SysMsg_SendBroadcastMsg("恭喜玩家【"..name.."】获得跑酷第"..num.."名奖励！！！！","跑酷奖励")
    return ""
end