---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2020/5/19 12:43
---
local timeNum =  0
function receive(player)
    local level = lualib:Level(player)
    if level < 75 then
        lualib:MsgBox(player,"您的等级不足！！请75级以后再来参加！")
        return ""
    end

    if lualib:GetDBNum("hegemony") == 1 then
        lualib:Player_MapMoveXY(player,"新西域",99,152,3)
    else
        lualib:MsgBox(player,"活动尚未开始！")
    end
    return ""
end

function active()
    local startTimeStr = lualib:GetConstVar("StartServerTime")      --开区时间字符串
    local startTime = lualib:Str2Time(startTimeStr)                 --开区时间
    local currentTimeStr = lualib:Now()                             --当前时间字符串
    local currentTime = lualib:Str2Time(currentTimeStr)                             --当前时间
    local activit = lualib:Str2Time("2020-05-01 16:26:00")                             --当前时间
    local fristTime = startTime % (24 * 60 * 60)
    local map = lualib:Map_GetMapGuid("新西域")
    --lualib:SysMsg_SendBroadcastMsg(tostring((currentTime - activit) % (24 * 60 * 60)) .. "\\" ..tostring(currentTime - startTime).."\\" ..tostring((24 * 60 * 60) - fristTime) ,"active")
    if (currentTime - activit) % (24 * 60 * 60) == 0 and (currentTime - startTime) > (24 * 60 * 60) - fristTime then
        lualib:SysMsg_SendBroadcastMsg("1111","1111")

        --lualib:SysMsg_SendBoardMsg("0", "[天下第一]", "天下第一争霸赛入场开始，请要参赛的玩家抓紧时间入场！", 15000)

        local dgn = lualib:Map_CreateDgn("天下第一战场", true, 3600 * 7)
        if dgn == "" then
            lualib:Error("副本：天下第一战场创建失败！")
            return
        end
        lualib:Error("副本：天下第一战场创建成功！")
        lualib:SetDBNum("hegemony",1)
        lualib:Map_SetCustomVarStr(map, "scheduled_txdyzc_dgn_guid", dgn)
        lualib:AddTimer("0", 202005252, 1000, -1, "hegemonyOver")
        timeNum = 0
        lualib:SysMsg_SendBoardMsg("0", "[天下第一]", "天下第一争霸赛入场开始，请要参赛的玩家抓紧时间入场！", 15000)
        timeNu = 0
    end
end

function hegemonyOver()
    timeNum = timeNum + 1
    if timeNum == 60*10 then
        lualib:SetDBNum("hegemony",0)
        lualib:DisableTimer("0",202005252)
    end
end
