---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2020/5/22 17:43
---
local timeNum =  0
function receive(player)
    local level = lualib:Level(player)
    if level < 50 then
        lualib:MsgBox(player,"您的等级不足！！请50级以后再来参加！")
        return ""
    end

    if lualib:GetDBNum("oshiba") == 1 then
        lualib:Player_MapMoveXY(player,"押镖地图",52,36,3)
    else
        lualib:MsgBox(player,"活动尚未开始！")
    end
    return ""
end

function active()
    local startTimeStr = lualib:GetConstVar("StartServerTime")      --开区时间字符串
    local startTime = lualib:Str2Time(startTimeStr)                 --开区时间
    local currentTimeStr = lualib:Now()                             --当前时间字符串
    local currentTime = lualib:Str2Time(currentTimeStr)                             --当前时间
    local activit = lualib:Str2Time("2020-05-01 19:30:00")                             --当前时间
    local fristTime = startTime % (24 * 60 * 60)

    if  (currentTime - activit) == 50 * 60 then
        lualib:AddTimer("0", 202005223, 1000, -1, "oshibaOver")
        lualib:SetDBNum("oshiba",1)
        return ""
    end

    if (currentTime - activit) % (24 * 60 * 60) == 0 and (currentTime - startTime) > (24 * 60 * 60) - fristTime then
        lualib:SetDBNum("oshiba",1)
        lualib:AddTimer("0", 202005223, 1000, -1, "oshibaOver")
        return ""
    end
    return ""
end

function oshibaOver()
    timeNum = timeNum + 1
    if timeNum == 60*30 then
        lualib:SetDBNum("oshiba",0)
        lualib:DisableTimer("0",202005221)
    end
end
