---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2020/5/19 15:24
---
function main(player,npc)
    local map = lualib:Map_GetMapGuid("ÃÏ¥Õ±¶œ‰")
    lualib:AddItem(player,"±¶œ‰",1,true,"ÃÏ¥Õ±¶œ‰npc","ÃÏ¥Õ±¶œ‰npc")
    local playerList = lualib:Map_GetMapPlayers(map, true)
    if #playerList == 0 then return end
    for k, v in pairs(playerList) do
        lualib:Player_MapMoveXY(v,"ÃÏ¥Õ±¶œ‰",79,158,3)
    end
    lualib:Npc_Remove(npc)
    return ""
end