---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2020/5/9 13:49
---
local lua_path = lualib:IO_GetLuaPath()
local package_path = package.path
package.path = string.format("%s;%s?.lua;%s?", package_path, lua_path, lua_path)
require("system/serializer")
local fashion = {
    {"吕布时装",1},
    {"海皇时装",1},
    {"许褚时装",1},
    {"大圣时装",1},
    {"赵云时装",1},
    {"吕布时装SS",2},
    {"海皇时装SS",2},
    {"许褚时装SS",2},
    {"大圣时装SS",2},
    {"赵云时装SS",2},
}

local setAttr = {   --普通时装一件属性，S时装一件的属性,普通时装的套装buff（少后面的数字直接在脚本中获取），S时装的套装buff(同上)，每件时装加的buff(同上)
    2,
    5,
    "普通套装",
    "S套装",
    "时装属性1",
    "时装属性2"
}

local setAttrs = {           --套装buff的keyname,增加的攻击伤害
    {"普通套装3",0.01},
    {"普通套装4",0.02},
    {"普通套装5",0.03},
    {"S套装3",0.01},
    {"S套装4",0.02},
    {"S套装5",0.03}
}

local accessTable = {}
function main(player)
    local str = ""
    local name  = lualib:KeyName(player)
    for i=1,25 do
        local num = lualib:GetDBNum(name.."depositFashion"..i)
        if num ==0 then
            accessTable[i] = 0
        else
            accessTable[i] = num
        end
    end
    str = "accessTable = " .. serialize(accessTable) .. ";fashion = " .. serialize(fashion)
    lualib:ShowFormWithContent(player,"脚本表单",str)
    lualib:ShowFormWithContent(player, "form文件表单", "时装仓库")
    return ""
end

function deposit(player,num)    --存入装备
    local number = tonumber(num)       --传回来的数据
    local name  = lualib:KeyName(player)
    local fashionName = 0       --存入第几件时装
    local str = ""
    local position = 0

    if lualib:GetDBNum(name.."depositFashion"..number) ~= 0 then
        lualib:MsgBox(player,"您的存入过物品，请勿重复存入")
        return ""
    end

    for i=1,#fashion do
        if  lualib:ItemCount(player,fashion[i][1]) > 0 then
            lualib:SetDBNumEx(name.."depositFashion"..number,i,2)
            lualib:DelItem(player,fashion[i][1],1,2,"时装存入","时装仓库表单")
            fashionName = i
            break
        end
    end

    if fashionName == 0 then
        lualib:MsgBox(player,"您的背包中没有可存入的时装！！")
        return ""
    end

    position = lualib:GetDBNum(name.."depositFashion"..number)
    str = "position = ".. serialize(position)..";number = " .. serialize(number)
    lualib:ShowFormWithContent(player,"脚本表单",str)
    lualib:ShowFormWithContent(player,"脚本表单",[[warehouse.update()]])
    attributes(player)
    return ""
end

function retrieve(player,num)   --取出装备
    local number = tonumber(num)
    local name  = lualib:KeyName(player)
    local str = ""
    local itemNum = lualib:GetDBNum(name.."depositFashion"..number)
    if itemNum == 0 then
        lualib:MsgBox(player,"您的没有存入物品！")
        return ""
    end
    lualib:SetDBNumEx(name.."depositFashion"..number,0,2)
    lualib:AddItem(player,fashion[itemNum][1],1,false,"取出时装","时装仓库表单")

    str = "number = " .. serialize(number)
    lualib:ShowFormWithContent(player,"脚本表单",str)
    lualib:ShowFormWithContent(player,"脚本表单",[[warehouse.fashionClear()]])
    attributes(player)
    return ""
end

function attributes(player)
    local name = lualib:KeyName(player)
    local ordinaryFashionNum = 0    --普通时装数量
    local SFashionNum = 0           --S级时装的数量
    local fashionAttrCount = 0      --时装数量所添加的物攻上下限（ordinaryFashionNum*setAttr[1] + SFashionNum*setAttr[1]）
    local fashionCount = 0          --普通时装数量（或S时装数量）可获得buff等级（最多为5）

    for i=1,25 do
        local num = lualib:GetDBNum(name.."depositFashion"..i)
        if num ~= 0 then
            if fashion[num][2] == 1 then
                ordinaryFashionNum = ordinaryFashionNum + 1
            elseif fashion[num][2] == 2 then
                SFashionNum = SFashionNum + 1
            end
        end
    end

    for i=1,5 do
        if lualib:HasBuff(player,setAttr[3]..i) then
            lualib:DelBuff(player,setAttr[3]..i)
        end
        if lualib:HasBuff(player,setAttr[4]..i) then
            lualib:DelBuff(player,setAttr[4]..i)
        end
    end

    if lualib:HasBuff(player,setAttr[5]) then
        lualib:DelBuff(player,setAttr[5])
    end

    if lualib:HasBuff(player,setAttr[6]) then
        lualib:DelBuff(player,setAttr[6])
    end

    fashionAttrCount = ordinaryFashionNum*setAttr[1] + SFashionNum*setAttr[2]

    local x = lualib:AddBuffEx(player,setAttr[5],0,fashionAttrCount)

    local x = lualib:AddBuffEx(player,setAttr[6],0,fashionAttrCount)
    fashionCount = math.floor(ordinaryFashionNum/5)
    if fashionCount ~= 0 then
        if fashionCount >5 then
            lualib:AddBuff(player,setAttr[3].."5", 0)
        else
            lualib:AddBuff(player,setAttr[3]..fashionCount, 0)
        end
    end

    fashionCount = math.floor(SFashionNum/5)
    if fashionCount ~= 0 then
        if fashionCount >5 then
            lualib:AddBuff(player,setAttr[3].."5", 0)
        else
            lualib:AddBuff(player,setAttr[3]..fashionCount, 0)
        end
    end
    return ""
end

function OnStateInit()
    if lualib:GetCurScriptName() == "时装仓库表单" then
        if not lualib:HasTrigger("0", lua_trigger_post_equip, "on_post_equip") then
            lualib:AddTrigger("0",	lua_trigger_role_pre_harm, "on_pre_harm")    --被攻击者受到伤害即将损血前回调
        end
    end
end

function on_pre_harm(role, attacker, hp, defense, skill_key)
    local multiple = 1
    for i=1,#setAttrs do
        if lualib:HasBuff(attacker,setAttrs[i][1]) then
            multiple = multiple + setAttrs[i][2]
        end
    end
    hp = math.floor(hp * multiple)
    return hp
end