---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2020/5/14 13:44
---
local lua_path = lualib:IO_GetLuaPath()
local package_path = package.path
package.path = string.format("%s;%s?.lua;%s?", package_path, lua_path, lua_path)
require("system/serializer")
require("system/timecount_def")

local timeNum = 0

-----------------------图标显示-----------------------------
function exciting_activities_show(player,line,pos)
    AddSEIcon(player, line, pos, "精彩活动", 1800200047, "精彩活动", "main", "", "精彩活动")
    return true
end

-------------------图标被点击-----------------------
function main(player)

    local data = ""
    lualib:ShowFormWithContent(player,"脚本表单",data)
    lualib:ShowFormWithContent(player, "form文件表单", "激情活动")
    return ""
end

function receive(player)
    if lualib:GetDBNum("passionateParty") == 1 then
        lualib:Player_MapMoveXY(player,"新西域",72,122,3)
    else
        lualib:MsgBox(player,"活动尚未开始！")
    end
    return ""
end

function activityTimer()
    local startTimeStr = lualib:GetConstVar("StartServerTime")      --开区时间字符串
    local startTime = lualib:Str2Time(startTimeStr)                 --开区时间
    local currentTimeStr = lualib:Now()                             --当前时间字符串
    local currentTime = lualib:Str2Time(currentTimeStr)                             --当前时间
    local activit = lualib:Str2Time("2020-05-01 16:03:00")                             --当前时间
    if (currentTime - startTime) / (35 *60) == 1 then
        lualib:SetDBNum("passionateParty",1)
        lualib:AddTimer("0", 20200516, 1000, -1, "精彩活动:activityOver")
        lualib:SysMsg_SendBroadcastMsg("激情派对活动开始了快来参加加活动吧！！","激情派对")
        timeNum = 0
    end
    if (currentTime - activit) % (24 * 60 * 60) == 0 and (currentTime - startTime) >= (24 * 60 * 60) then
        lualib:SetDBNum("passionateParty",1)
        lualib:AddTimer("0", 20200516, 1000, -1, "精彩活动:activityOver")
        lualib:SysMsg_SendBroadcastMsg("激情派对活动开始了快来参加加活动吧！！","激情派对")
        timeNum = 0
    end
    return ""
end

function activityOver()
    timeNum = timeNum + 1
    local map = lualib:Map_GetMapGuid("新西域")
    if timeNum == 1 then
        lualib:GSRunScript("精彩活动:clientEffects","")
    elseif timeNum == 60 * 5 then
        lualib:DisableTimer("0",20200516)
        lualib:SetDBNum("passionateParty",0)

        timeNum = 0
        lualib:SysMsg_SendBroadcastMsg("激情派对活动结束！如想再次参加请等下次活动开始！！","激情派对")
        lualib:SysMsg_SendBroadcastMsg("激情派对活动结束！如想再次参加请等下次活动开始！！","激情派对")
        lualib:SysMsg_SendBroadcastMsg("激情派对活动结束！如想再次参加请等下次活动开始！！","激情派对")
        return ""
    end

    local playerTable = lualib:Map_GetMapPlayers(map,true)
    for k,v in pairs(playerTable) do
        local x = lualib:X(v)
        local y = lualib:Y(v)
        if x >= 68 and x <= 73 and y >= 117 and y <= 125 then
            if x == 70 and y == 120 then
                lualib:AddExp(v,4000000,"激情派对","精彩活动")
                lualib:AddIngot(v,10,"激情派对","精彩活动")
            else
                lualib:AddExp(v,2000000,"激情派对","精彩活动")
                lualib:AddIngot(v,2,"激情派对","精彩活动")
            end
        end
    end
    return ""
end

function clientEffects(player)
    local magicid = 300000501
    local speed = 1000
    local life = 1000 * 5 * 60
    for i = 1 , 6 do
        for j = 1, 9 do
            local x = 68
            local y = 117
            x = x + (i - 1)
            y = y + (j - 1)
            if x == 68  or y == 117 or x==73 or y == 125 then       --68 73 117 125
                lualib:RunClientScript(player, "ItemEffect", "texiao", magicid.."#"..x.."#"..y.."#"..speed.."#"..life)
            end
        end
    end
    return ""
end