---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ya.
--- DateTime: 2020/5/29 12:41
---
local lua_path = lualib:IO_GetLuaPath()
local package_path = package.path
package.path = string.format("%s;%s?.lua;%s?", package_path, lua_path, lua_path)
require("system/serializer")
require("system/timecount_def")

local accumulateGift = {
    {30,{"战魂1","经验丹","耀光精魄","金针","赵云时装","血符碎片"}},
    {50,{"战魂1","经验丹", "耀光精魄", "金针", "赵云时装","血符碎片"}},
    {100,{"战魂1", "经验丹", "耀光精魄", "金针", "赵云时装", "血符碎片" }},
    {300,{"战魂1", "经验丹", "耀光精魄", "金针", "赵云时装", "血符碎片" }},
    {500,{"战魂1", "经验丹", "耀光精魄", "金针", "赵云时装", "血符碎片" }},
    {1000,{"战魂1", "经验丹", "耀光精魄", "金针", "赵云时装", "血符碎片" }},
    {2000,{"战魂1", "经验丹", "耀光精魄", "金针", "赵云时装", "血符碎片" }},
    {3000,{"战魂1", "经验丹", "耀光精魄", "金针", "赵云时装", "血符碎片" }},
    {5000,{"战魂1", "经验丹", "耀光精魄", "金针", "赵云时装", "血符碎片" }},
    {10000,{"战魂1", "经验丹", "耀光精魄", "金针", "赵云时装", "血符碎片" }},
    {20000,{"战魂1", "经验丹", "耀光精魄", "金针", "赵云时装", "血符碎片" }},
    {30000,{"战魂1", "经验丹", "耀光精魄", "金针", "赵云时装", "血符碎片" }},
    {50000,{"战魂1", "经验丹", "耀光精魄", "金针", "赵云时装", "血符碎片" }},
    {100000,{"战魂1", "经验丹", "耀光精魄", "金针", "赵云时装", "血符碎片" }}
}

local accumulateGiftCount = {   --对应accumulateGift【】【2】中物品数量
    {1,50,100,100,1,1000},
    {1,50,100,100,1,1000},
    {1,50,100,100,1,1000},
    {1,50,100,100,1,1000},
    {1,50,100,100,1,1000},
    {1,50,100,100,1,1000},
    {1,50,100,100,1,1000},
    {1,50,100,100,1,1000},
    {1,50,100,100,1,1000},
    {1,50,100,100,1,1000},
    {1,50,100,100,1,1000},
    {1,50,100,100,1,1000},
    {1,50,100,100,1,1000},
    {1,50,100,100,1,1000},
}

local accumulateGiftBindin  = {--对应物品是否绑定（绑定类型, 0 = 非绑定 1 = 绑定 2 = 绑定/非绑定.）
    {0,0,0,0,0,0},
    {0,0,0,0,0,0},
    {0,0,0,0,0,0},
    {0,0,0,0,0,0},
    {0,0,0,0,0,0},
    {0,0,0,0,0,0},
    {0,0,0,0,0,0},
    {0,0,0,0,0,0},
    {0,0,0,0,0,0},
    {0,0,0,0,0,0},
    {0,0,0,0,0,0},
    {0,0,0,0,0,0},
    {0,0,0,0,0,0},
    {0,0,0,0,0,0}
}

local accumulateGiftAdd = {0,0,0,0,0,0} --对应物品是够添加（0 = 添加 1 = 删除.）

-----------------------图标显示-----------------------------
function accumulate(player,line,pos)
    AddSEIcon(player, line, pos, "累充礼包", 1800200227, "累充礼包", "main", "", "累充礼包")
    return true
end

-------------------图标被点击-----------------------
function main(player)
    local canClaim = 0                                                          --可以领取的次数
    local peak = 0                                                              --全部显示时
    local str = ""
    local id  =  lualib:UserID(player)
    local ingots = lualib:GetDBNum("ljcz"..id)                                  --累计充值
    local receiveNum = lualib:GetDBNum("receiveNum"..id)                        --已经领取的次数
    ingots = math.floor(ingots/100)
    for i = 1,#accumulateGift do
        if ingots >= accumulateGift[i][1] then
            if i < 6 then
                canClaim = 6
            else
                canClaim = i + 1
            end

            if i == #accumulateGift or i == (#accumulateGift - 1)  then
                canClaim = #accumulateGift
            end
            peak = i
        end
    end
    if canClaim == 0 then
        canClaim = 6
        peak = 0
    end

    str = "accumulateGift = " .. serialize(accumulateGift)..";accumulateGiftCount = " .. serialize(accumulateGiftCount) ..";canClaim = " .. serialize(canClaim) ..";peak = " .. serialize(peak) ..";receiveNum = " .. serialize(receiveNum) ..";ingots = " .. serialize(ingots)
    lualib:ShowFormWithContent(player,"脚本表单",str)
    lualib:ShowFormWithContent(player, "form文件表单", "累充礼包")
    return ""
end

function receive(player,num)
    local num = tonumber(num)
    local id  =  lualib:UserID(player)
    local ingots = lualib:GetDBNum("ljcz"..id)                                  --累计充值
    local receiveNum = lualib:GetDBNum("receiveNum"..id)                        --已经领取的次数
    local data = ""
    if accumulateGift[num][1] > ingots then
        lualib:MsgBox(player,"您的充值未达到！！请勿修改客户端！！")
        return ""
    end

    if receiveNum >= num then
        lualib:MsgBox(player,"您已经领取过了！！请勿修改客户端！！")
        return ""
    end

    if num > receiveNum + 1 then
        lualib:MsgBox(player,"请按顺序领取！！")
        return ""
    end

    if not lualib:Player_ItemRequest(player, accumulateGift[num][2], accumulateGiftCount[num], accumulateGiftBindin[num], accumulateGiftAdd, "事务操作：累充礼包奖励", "累充礼包") then
        lualib:SysMsg_SendWarnMsg(player, keyname.."使用失败，背包已满！")
        return false
    end

    lualib:SetDBNumEx("receiveNum"..id,lualib:GetDBNum("receiveNum"..id)+1,2)
    receiveNum = lualib:GetDBNum("receiveNum"..id)
    data = "receiveNum = " .. serialize(receiveNum)
    lualib:ShowFormWithContent(player,"脚本表单",data)
    lualib:ShowFormWithContent(player,"脚本表单",[[accumulate.update()]])
    return ""
end