---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2020/5/19 12:43
---
local timeNum =  0
function receive(player)
    local level = lualib:Level(player)
    if level < 70 then
        lualib:MsgBox(player,"您的等级不足！！请75级以后再来参加！")
        return ""
    end

    if lualib:GetDBNum("guild") == 1 then
        lualib:Player_MapMoveXY(player,"新西域",111,163,3)
    else
        lualib:MsgBox(player,"活动尚未开始！")
    end
    return ""
end

function active()
    local startTimeStr = lualib:GetConstVar("StartServerTime")      --开区时间字符串
    local startTime = lualib:Str2Time(startTimeStr)                 --开区时间
    local currentTimeStr = lualib:Now()                             --当前时间字符串
    local currentTime = lualib:Str2Time(currentTimeStr)                             --当前时间
    local activit = lualib:Str2Time("2020-05-01 12:35:00")                             --当前时间
    local fristTime = startTime % (24 * 60 * 60)
    local map = lualib:Map_GetMapGuid("新西域")

    lualib:SysMsg_SendBroadcastMsg("fristTime" ,"active")
    if (currentTime - activit) % (24 * 60 * 60) == 0 and (currentTime - startTime) > (24 * 60 * 60) - fristTime then
        lualib:AddTimer("0", 202005251, 1000, -1, "guildOver")
        lualib:SetDBNum("guild",1)
        timeNum =0
        lualib:SetStr("0","Mrrp_行会争霸S0", "开启")
        lualib:SetDBStrEx("Mrrp_行会争霸S1", "", 6)
        lualib:SetStr("0","行会争霸临时占领", "")
        local map_guid = lualib:Map_GetMapGuid("行会争霸场地")
        lualib:AddTimer(map_guid, 1, 5000, -1, "hanghuizhengba")
        lualib:GSRunScript("行会争霸入场:on_campaign_start", "")
        lualib:SysMsg_SendBroadcastColor("行会争霸赛开始了，有实力的行会请到【西域（100，149）】找到行会争霸NPC参加战斗！", "", 2, 1)
        lualib:SysMsg_SendBroadcastColor("行会争霸赛开始了，有实力的行会请到【西域（100，149）】找到行会争霸NPC参加战斗！", "", 2, 1)
        lualib:SysMsg_SendBroadcastColor("行会争霸赛开始了，有实力的行会请到【西域（100，149）】找到行会争霸NPC参加战斗！", "", 2, 1)
    end
    if (currentTime - activit) % (24 * 60 * 60 - 5*60) == 0 and (currentTime - startTime) > (24 * 60 * 60) - fristTime then
        lualib:SysMsg_SendBroadcastColor("行会争霸赛快要开始了，还有5分钟活动开始有实力的行会请到【西域（100，149）】找到行会争霸NPC参加战斗！", "", 2, 1)
    end
end

function guildOver()
    timeNum = timeNum + 1
    if timeNum == 60*10 then
        lualib:SetDBNum("guild",0)
        lualib:DisableTimer("0",202005251)
        lualib:SetStr("0","Mrrp_行会争霸S0", "关门")
        lualib:SetDBStrEx("Mrrp_行会争霸S1", "", 6)
        lualib:SysMsg_SendBroadcastColor("行会争霸已关闭进入，坚持到最后的行会将是胜利者！将是谁呢？让我们拭目以待！", "", 2, 1)
        lualib:SysMsg_SendBroadcastColor("行会争霸已关闭进入，坚持到最后的行会将是胜利者！将是谁呢？让我们拭目以待！", "", 2, 1)
        lualib:SysMsg_SendBroadcastColor("行会争霸已关闭进入，坚持到最后的行会将是胜利者！将是谁呢？让我们拭目以待！", "", 2, 1)
    end
    if timeNum == 60*9 then
        lualib:SysMsg_SendBroadcastColor("行会争霸快要关闭了，还有1分钟请需要参加活动的行会请到【西域（100，149）】找到行会争霸NPC参加战斗！", "", 2, 1)
    end
end
