---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2020/5/28 14:45
---

local lua_path = lualib:IO_GetLuaPath()
local package_path = package.path
package.path = string.format("%s;%s?.lua;%s?", package_path, lua_path, lua_path)
require("system/serializer")
require("system/timecount_def")

local demandIngot = 30*100      --首充需要的充值元宝数
local satisfy = 0               --是否满足需求的充值
local rewardItem = {
    {"战魂10",1},
    {"战魂10",1},
    {"战魂10",1},
    {"战魂10",1}
}
-----------------------图标显示-----------------------------
function firstCharge(player,line,pos)
    AddSEIcon(player, line, pos, "首充礼包", 1800200023, "首充礼包", "main", "", "首充礼包")
    return true
end

-------------------图标被点击-----------------------
function main(player)
    local id = lualib:UserID(player)

    if lualib:GetDBNum("ljcz"..id) >= demandIngot then
        satisfy = 1
    else
        satisfy = 0
    end
    local str = "satisfy = " .. serialize(satisfy) ..";rewardItem = " .. serialize(rewardItem)
    lualib:ShowFormWithContent(player,"脚本表单",str)
    lualib:ShowFormWithContent(player, "form文件表单", "首充礼包")
    return ""
end

function receive(player)
    local id = lualib:UserID(player)
    if lualib:GetDBNum("ljcz"..id) < demandIngot then
        lualib:MsgBox(player,"您的充值不足30元!!!!请勿修改客户端！！")
        return ""
    end
    if lualib:GetDBNum("firstCharge"..id) == 1 then
        lualib:MsgBox(player,"您已经领取过该奖励！！！请勿重复点击！！")
        return ""
    end
    for i=1,#rewardItem do
        if not lualib:AddSingleItem(player, rewardItem[i][1], rewardItem[i][2], 1, "首充礼包给予物品", "首充礼包") then
            lualib:MsgBox(player,"领取物品失败！！请联系客服处理！！")
        end
    end
    lualib:SetDBNumEx("firstCharge"..id,1,2)
    lualib:SysMsg_SendBroadcastMsg("恭喜玩家【"..lualib:KeyName(player).."领取了首充礼包！！！】","首充奖励")
    lualib:SysMsg_SendBroadcastMsg("恭喜玩家【"..lualib:KeyName(player).."领取了首充礼包！！！】","首充奖励")
    lualib:SysMsg_SendBroadcastMsg("恭喜玩家【"..lualib:KeyName(player).."领取了首充礼包！！！】","首充奖励")
    lualib:MsgBox(player,"领取成功")
    return ""
end