---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2020/3/5 21:06
---

<form>
    <dialog id="test" image="1857420100,1857420102,1857420106,1857420108,1857420104,1857420101,1857420107,1857420103,1857420105" w="792" h="570" fitsize="true" esc_close="true" close="false" center="true"  drag="true" OnInit="test.Initialize">
    <image id="bgk1" image="1857400100" x="0" y="0" w="792" h="40" />
    <image id="bgk2" image="1856700000" x="4" y="40" w="786" h="526" fitsize=true/>
    <image id="bgk3" image="1857420100,1857420102,1857420106,1857420108,1857420104,1857420101,1857420107,1857420103,1857420105" x=40 y=100 w=710 h=450 fitsize=true/>
    
    <button id="colseBtn" image="1857410000" x="674" y="-27" w="139" h="128" OnLButtonClick="test.close"/>
    <wnd id=pagWnd1 x=40 y=60 w=710 h=490>
    <wnd id=showWnd2 x=0 y=40 w=710 h=480>
    </wnd>

    <wnd id=showWnd1 x=0 y=40 w=710 h=480>
    </wnd>
</wnd>
</dialog>
<script><![CDATA[
	
]]></script>
</form>